// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import {
    Box,
    BoxUtil,
    FreBoxProvider,
    FreProjectionHandler,
    FreNodeReference,
    type FreNamedNode,
    BoxFactory,
    createDefaultExpressionBox,
} from "@freon4dsl/core";
import { CountExpression, Event } from "../language/index.js";

import { LanguageEnvironment } from "../index.js";

/**
 * This class implements the box provider for a single node of type CountExpression.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class CountExpressionBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default"];
        this.knownTableProjections = ["default"];
        this.conceptName = "CountExpression";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return createDefaultExpressionBox(
            this._node as CountExpression,
            [
                BoxFactory.horizontalLayout(
                    this._node as CountExpression,
                    "CountExpression-hlist-line-0",
                    "",
                    [
                        BoxUtil.labelBox(this._node as CountExpression, "count(", "top-1-line-0-item-0"),
                        BoxUtil.referenceBox(
                            this._node as CountExpression,
                            "event",
                            (selected: string | FreNamedNode) => {
                                const ref =
                                    typeof selected === "string"
                                        ? FreNodeReference.create<Event>(selected, "Event")
                                        : FreNodeReference.create<Event>(selected as Event, "Event");
                                (this._node as CountExpression).event = ref;
                            },
                            LanguageEnvironment.getInstance().scoper,
                        ),
                        BoxUtil.labelBox(this._node as CountExpression, ")", "top-1-line-0-item-2"),
                    ],
                    { selectable: false },
                ),
            ],
            { selectable: false },
        );
    }
}
