// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import {
    Box,
    BoxUtil,
    FreBoxProvider,
    FreProjectionHandler,
    BoxFactory,
    FreListInfo,
    FragmentBox,
    FreNodeReference,
    LimitedDisplay,
} from "@freon4dsl/core";
import { Event, TypeOfEvent } from "../language/index.js";

import { LanguageEnvironment } from "../index.js";

/**
 * This class implements the box provider for a single node of type Event.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class EventBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["checklistsShow", "default", "parser", "schedulingAndChecklistsShow", "schedulingShow"];
        this.knownTableProjections = ["default"];
        this.conceptName = "Event";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "checklistsShow") {
                return this.getChecklistsShow();
            } else if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            } else if (projectionName === "schedulingAndChecklistsShow") {
                return this.getSchedulingAndChecklistsShow();
            } else if (projectionName === "schedulingShow") {
                return this.getSchedulingShow();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getChecklistsShow(): Box {
        return BoxUtil.fragmentWrapperBox(this._node as Event, "ItemGroupComponent", this.getFragmentBox_checklistEventDetails(), {
            params: [
                { key: "cssClass", value: "type2" },
                { key: "canDelete", value: "true" },
                { key: "canDuplicate", value: "true" },
                { key: "canExpand", value: "true" },
                { key: "isExpanded", value: "false" },
                { key: "selectable", value: "false" },
                { key: "label", value: "Event" },
            ],
        });
    }

    private getDefault(): Box {
        return BoxUtil.fragmentWrapperBox(this._node as Event, "ItemGroupComponent", this.getFragmentBox_noEventDetails(), {
            params: [
                { key: "cssClass", value: "type2" },
                { key: "canDelete", value: "true" },
                { key: "canDuplicate", value: "true" },
                { key: "canExpand", value: "true" },
                { key: "isExpanded", value: "false" },
                { key: "selectable", value: "false" },
                { key: "label", value: "Event" },
            ],
        });
    }

    private getParser(): Box {
        return BoxFactory.verticalLayout(
            this._node as Event,
            "Event-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as Event,
                    "Event-hlist-line-0",
                    "",
                    [BoxUtil.labelBox(this._node as Event, "Event:", "top-1-line-0-item-0"), BoxUtil.textBox(this._node as Event, "name")],
                    { selectable: false },
                ),
                BoxFactory.horizontalLayout(
                    this._node as Event,
                    "Event-hlist-line-1",
                    "",
                    [
                        BoxUtil.labelBox(this._node as Event, "This is a", "top-1-line-1-item-0"),
                        BoxUtil.limitedBox(
                            this._node as Event,
                            "typeOfEvent",
                            (selected: string | TypeOfEvent) => {
                                (this._node as Event).typeOfEvent = FreNodeReference.create<TypeOfEvent>(selected, "TypeOfEvent");
                            },
                            LimitedDisplay.SELECT,
                            LanguageEnvironment.getInstance().scoper,
                        ),
                        BoxFactory.optional(
                            this._node as Event,
                            "optional-alternativeName",
                            () => !!(this._node as Event).alternativeName,
                            BoxFactory.horizontalLayout(
                                this._node as Event,
                                "Event-optional-alternativeName-hlist-line-0",
                                "",
                                [
                                    BoxUtil.labelBox(this._node as Event, "that is also referred to as", "top-2-line-0-item-0"),
                                    BoxUtil.textBox(this._node as Event, "alternativeName"),
                                ],
                                { selectable: false },
                            ),
                            false,
                            BoxFactory.action(this._node, "optional-alternativeName", "that is also referred to as"),
                        ),
                    ],
                    { selectable: false },
                ),
                BoxUtil.getBoxOrAction(this._node as Event, "description", "Description", this.mainHandler),
                BoxUtil.labelBox(this._node as Event, "Schedule:", "top-1-line-3-item-0"),
                BoxUtil.indentBox(
                    this._node as Event,
                    2,
                    "4",
                    BoxUtil.getBoxOrAction(this._node as Event, "schedule", "EventSchedule", this.mainHandler),
                ),
                BoxUtil.labelBox(this._node as Event, "Tasks:", "top-1-line-5-item-0"),
                BoxUtil.indentBox(
                    this._node as Event,
                    2,
                    "6",
                    BoxUtil.verticalPartListBox(
                        this._node as Event,
                        (this._node as Event).tasks,
                        "tasks",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
            ],
            { cssClass: "Event" },
        );
    }

    private getSchedulingAndChecklistsShow(): Box {
        return BoxUtil.fragmentWrapperBox(
            this._node as Event,
            "ItemGroupComponent",
            this.getFragmentBox_schedulingAndChecklistsEventDetails(),
            {
                params: [
                    { key: "cssClass", value: "type2" },
                    { key: "canDelete", value: "true" },
                    { key: "canDuplicate", value: "true" },
                    { key: "canExpand", value: "true" },
                    { key: "isExpanded", value: "false" },
                    { key: "selectable", value: "false" },
                    { key: "label", value: "Event" },
                ],
            },
        );
    }

    private getSchedulingShow(): Box {
        return BoxUtil.fragmentWrapperBox(this._node as Event, "ItemGroupComponent", this.getFragmentBox_schedulingEventDetails(), {
            params: [
                { key: "cssClass", value: "type2" },
                { key: "canDelete", value: "true" },
                { key: "canDuplicate", value: "true" },
                { key: "canExpand", value: "true" },
                { key: "isExpanded", value: "true" },
                { key: "selectable", value: "false" },
                { key: "label", value: "Event" },
            ],
        });
    }

    private getFragmentBox_checklistEventDetails(): FragmentBox {
        return new FragmentBox(
            this._node as Event,
            "Event-fragment-checklistEventDetails",
            BoxFactory.verticalLayout(
                this._node as Event,
                "Event-fragment-checklistEventDetails-overall",
                "",
                [
                    BoxUtil.textBox(this._node as Event, "name"),
                    BoxFactory.horizontalLayout(
                        this._node as Event,
                        "Event-fragment-checklistEventDetails-hlist-line-1",
                        "",
                        [
                            BoxUtil.labelBox(this._node as Event, "This is a", "top-1-line-1-item-0"),
                            BoxUtil.refReplacerBox(this._node as Event, "typeOfEvent", "CustomSelectComponent", {
                                params: [{ key: "placeholder", value: "event type" }],
                            }),
                            ,
                            BoxUtil.labelBox(this._node as Event, "that is also referred to as", "top-1-line-1-item-2"),
                            BoxUtil.textBox(this._node as Event, "alternativeName"),
                        ],
                        { selectable: false },
                    ),
                    BoxUtil.getBoxOrAction(this._node as Event, "description", "Description", this.mainHandler),
                    BoxUtil.partListWrapperBox(
                        this._node as Event,
                        "tasks",
                        "ListGroupComponent",
                        BoxUtil.verticalPartListBox(
                            this._node as Event,
                            (this._node as Event).tasks,
                            "tasks",
                            FreListInfo.NullListInfo,
                            this.mainHandler,
                        ),
                        {
                            params: [
                                { key: "cssClass", value: "type3" },
                                { key: "canAdd", value: "true" },
                                { key: "canDelete", value: "true" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "true" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Checklist" },
                            ],
                        },
                    ),
                ],
                { cssClass: "Event-fragment-checklistEventDetails" },
            ),
            { cssClass: "Event-fragment-checklistEventDetails" },
        );
    }

    private getFragmentBox_noEventDetails(): FragmentBox {
        return new FragmentBox(
            this._node as Event,
            "Event-fragment-noEventDetails",
            BoxFactory.verticalLayout(
                this._node as Event,
                "Event-fragment-noEventDetails-overall",
                "",
                [
                    BoxUtil.textBox(this._node as Event, "name"),
                    BoxFactory.horizontalLayout(
                        this._node as Event,
                        "Event-fragment-noEventDetails-hlist-line-1",
                        "",
                        [
                            BoxUtil.labelBox(this._node as Event, "This is a", "top-1-line-1-item-0"),
                            BoxUtil.refReplacerBox(this._node as Event, "typeOfEvent", "CustomSelectComponent", {
                                params: [{ key: "placeholder", value: "event" }],
                            }),
                            ,
                            BoxUtil.labelBox(this._node as Event, "that is also referred to as", "top-1-line-1-item-2"),
                            BoxUtil.textBox(this._node as Event, "alternativeName"),
                        ],
                        { selectable: false },
                    ),
                    BoxUtil.getBoxOrAction(this._node as Event, "description", "Description", this.mainHandler),
                ],
                { cssClass: "Event-fragment-noEventDetails" },
            ),
            { cssClass: "Event-fragment-noEventDetails" },
        );
    }

    private getFragmentBox_schedulingAndChecklistsEventDetails(): FragmentBox {
        return new FragmentBox(
            this._node as Event,
            "Event-fragment-schedulingAndChecklistsEventDetails",
            BoxFactory.verticalLayout(
                this._node as Event,
                "Event-fragment-schedulingAndChecklistsEventDetails-overall",
                "",
                [
                    BoxUtil.textBox(this._node as Event, "name"),
                    BoxFactory.horizontalLayout(
                        this._node as Event,
                        "Event-fragment-schedulingAndChecklistsEventDetails-hlist-line-1",
                        "",
                        [
                            BoxUtil.labelBox(this._node as Event, "This is a", "top-1-line-1-item-0"),
                            BoxUtil.refReplacerBox(this._node as Event, "typeOfEvent", "CustomSelectComponent", {
                                params: [{ key: "placeholder", value: "event type" }],
                            }),
                            ,
                            BoxUtil.labelBox(this._node as Event, "that is also referred to as", "top-1-line-1-item-2"),
                            BoxUtil.textBox(this._node as Event, "alternativeName"),
                        ],
                        { selectable: false },
                    ),
                    BoxUtil.getBoxOrAction(this._node as Event, "description", "Description", this.mainHandler),
                    BoxUtil.partWrapperBox(
                        this._node as Event,
                        "schedule",
                        "ListGroupComponent",
                        BoxUtil.getBoxOrAction(this._node as Event, "schedule", "EventSchedule", this.mainHandler),
                        {
                            params: [
                                { key: "cssClass", value: "type3" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "false" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Schedule" },
                            ],
                        },
                    ),
                    BoxUtil.partListWrapperBox(
                        this._node as Event,
                        "tasks",
                        "ListGroupComponent",
                        BoxUtil.verticalPartListBox(
                            this._node as Event,
                            (this._node as Event).tasks,
                            "tasks",
                            FreListInfo.NullListInfo,
                            this.mainHandler,
                        ),
                        {
                            params: [
                                { key: "cssClass", value: "type3" },
                                { key: "canAdd", value: "true" },
                                { key: "canDelete", value: "true" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "true" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Checklist" },
                            ],
                        },
                    ),
                ],
                { cssClass: "Event-fragment-schedulingAndChecklistsEventDetails" },
            ),
            { cssClass: "Event-fragment-schedulingAndChecklistsEventDetails" },
        );
    }

    private getFragmentBox_schedulingEventDetails(): FragmentBox {
        return new FragmentBox(
            this._node as Event,
            "Event-fragment-schedulingEventDetails",
            BoxFactory.verticalLayout(
                this._node as Event,
                "Event-fragment-schedulingEventDetails-overall",
                "",
                [
                    BoxUtil.textBox(this._node as Event, "name"),
                    BoxFactory.horizontalLayout(
                        this._node as Event,
                        "Event-fragment-schedulingEventDetails-hlist-line-1",
                        "",
                        [
                            BoxUtil.labelBox(this._node as Event, "This is a", "top-1-line-1-item-0"),
                            BoxUtil.refReplacerBox(this._node as Event, "typeOfEvent", "CustomSelectComponent", {
                                params: [{ key: "placeholder", value: "event type" }],
                            }),
                            ,
                            BoxUtil.labelBox(this._node as Event, "that is also referred to as", "top-1-line-1-item-2"),
                            BoxUtil.textBox(this._node as Event, "alternativeName"),
                        ],
                        { selectable: false },
                    ),
                    BoxUtil.getBoxOrAction(this._node as Event, "description", "Description", this.mainHandler),
                    BoxUtil.partWrapperBox(
                        this._node as Event,
                        "schedule",
                        "ListGroupComponent",
                        BoxUtil.getBoxOrAction(this._node as Event, "schedule", "EventSchedule", this.mainHandler),
                        {
                            params: [
                                { key: "cssClass", value: "type3" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "true" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Schedule" },
                            ],
                        },
                    ),
                ],
                { cssClass: "Event-fragment-schedulingEventDetails" },
            ),
            { cssClass: "Event-fragment-schedulingEventDetails" },
        );
    }
}
