// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory, FreListInfo } from "@freon4dsl/core";
import { PatientHistory } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type PatientHistory.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class PatientHistoryBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "PatientHistory";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.verticalLayout(
            this._node as PatientHistory,
            "PatientHistory-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as PatientHistory,
                    "PatientHistory-hlist-line-0",
                    "",
                    [
                        BoxUtil.labelBox(this._node as PatientHistory, "ID", "top-1-line-0-item-0"),
                        BoxUtil.textBox(this._node as PatientHistory, "patient_id"),
                    ],
                    { selectable: false },
                ),
                BoxUtil.partListWrapperBox(
                    this._node as PatientHistory,
                    "patientVisits",
                    "ListGroupComponent",
                    BoxUtil.verticalPartListBox(
                        this._node as PatientHistory,
                        (this._node as PatientHistory).patientVisits,
                        "patientVisits",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                    {
                        params: [
                            { key: "cssClass", value: "type3" },
                            { key: "canAdd", value: "true" },
                            { key: "canExpand", value: "true" },
                            { key: "isExpanded", value: "true" },
                            { key: "selectable", value: "false" },
                            { key: "label", value: "Patient Visits" },
                        ],
                    },
                ),
                BoxUtil.partListWrapperBox(
                    this._node as PatientHistory,
                    "patientNotAvailableDates",
                    "ListGroupComponent",
                    BoxUtil.verticalPartListBox(
                        this._node as PatientHistory,
                        (this._node as PatientHistory).patientNotAvailableDates,
                        "patientNotAvailableDates",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                    {
                        params: [
                            { key: "cssClass", value: "type3" },
                            { key: "canAdd", value: "true" },
                            { key: "canExpand", value: "true" },
                            { key: "isExpanded", value: "true" },
                            { key: "selectable", value: "false" },
                            { key: "label", value: "Patient Not Available Dates" },
                        ],
                    },
                ),
            ],
            { cssClass: "PatientHistory" },
        );
    }

    private getParser(): Box {
        return BoxFactory.verticalLayout(
            this._node as PatientHistory,
            "PatientHistory-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as PatientHistory,
                    "PatientHistory-hlist-line-0",
                    "",
                    [
                        BoxUtil.labelBox(this._node as PatientHistory, "Patient ID:", "top-1-line-0-item-0"),
                        BoxUtil.textBox(this._node as PatientHistory, "patient_id"),
                    ],
                    { selectable: false },
                ),
                BoxUtil.indentBox(
                    this._node as PatientHistory,
                    1,
                    "1",
                    BoxUtil.labelBox(this._node as PatientHistory, "Visits:", "top-1-line-1-item-0"),
                ),
                BoxUtil.indentBox(
                    this._node as PatientHistory,
                    3,
                    "2",
                    BoxUtil.verticalPartListBox(
                        this._node as PatientHistory,
                        (this._node as PatientHistory).patientVisits,
                        "patientVisits",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
                BoxUtil.indentBox(
                    this._node as PatientHistory,
                    1,
                    "3",
                    BoxUtil.labelBox(this._node as PatientHistory, "Not Available Dates:", "top-1-line-3-item-0"),
                ),
                BoxUtil.indentBox(
                    this._node as PatientHistory,
                    3,
                    "4",
                    BoxUtil.verticalPartListBox(
                        this._node as PatientHistory,
                        (this._node as PatientHistory).patientNotAvailableDates,
                        "patientNotAvailableDates",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
            ],
            { cssClass: "PatientHistory" },
        );
    }
}
