// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, NumberDisplay, BoxFactory } from "@freon4dsl/core";
import { RepeatCondition } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type RepeatCondition.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class RepeatConditionBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "RepeatCondition";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.horizontalLayout(
            this._node as RepeatCondition,
            "RepeatCondition-hlist-line-0",
            "",
            [
                BoxUtil.labelBox(this._node as RepeatCondition, "repeats", "top-1-line-0-item-0"),
                BoxUtil.partReplacerBox(this._node as RepeatCondition, "repeatUnit", "CustomSelectComponent", {
                    params: [{ key: "placeholder", value: "frequency" }],
                }),
                ,
                BoxUtil.labelBox(this._node as RepeatCondition, "up to", "top-1-line-0-item-2"),
                BoxUtil.numberReplacerBox(this._node as RepeatCondition, "maxRepeats", "CustomNumericComponent", {
                    params: [
                        { key: "min", value: "2" },
                        { key: "max", value: "999" },
                        { key: "defaultValue", value: "1" },
                    ],
                }),
                BoxUtil.labelBox(this._node as RepeatCondition, "times", "top-1-line-0-item-4"),
                BoxFactory.optional(
                    this._node as RepeatCondition,
                    "optional-until",
                    () => !!(this._node as RepeatCondition).until,
                    BoxFactory.horizontalLayout(
                        this._node as RepeatCondition,
                        "RepeatCondition-optional-until-hlist-line-0",
                        "",
                        [
                            BoxUtil.labelBox(this._node as RepeatCondition, "until", "top-2-line-0-item-0"),
                            BoxUtil.getBoxOrAction(this._node as RepeatCondition, "until", "ScheduleExpression", this.mainHandler),
                        ],
                        { selectable: false },
                    ),
                    false,
                    BoxFactory.action(this._node, "optional-until", "until"),
                ),
            ],
            { selectable: false },
        );
    }

    private getParser(): Box {
        return BoxFactory.horizontalLayout(
            this._node as RepeatCondition,
            "RepeatCondition-hlist-line-0",
            "",
            [
                BoxUtil.getBoxOrAction(this._node as RepeatCondition, "repeatUnit", "RepeatUnit", this.mainHandler),
                BoxFactory.optional(
                    this._node as RepeatCondition,
                    "optional-maxRepeats",
                    () => !!(this._node as RepeatCondition).maxRepeats,
                    BoxFactory.horizontalLayout(
                        this._node as RepeatCondition,
                        "RepeatCondition-optional-maxRepeats-hlist-line-0",
                        "",
                        [
                            BoxUtil.labelBox(this._node as RepeatCondition, "up to", "top-2-line-0-item-0"),
                            BoxUtil.numberBox(this._node as RepeatCondition, "maxRepeats", NumberDisplay.SELECT),
                            BoxUtil.labelBox(this._node as RepeatCondition, "times", "top-2-line-0-item-2"),
                        ],
                        { selectable: false },
                    ),
                    false,
                    BoxFactory.action(this._node, "optional-maxRepeats", "up to"),
                ),
                BoxFactory.optional(
                    this._node as RepeatCondition,
                    "optional-until",
                    () => !!(this._node as RepeatCondition).until,
                    BoxFactory.horizontalLayout(
                        this._node as RepeatCondition,
                        "RepeatCondition-optional-until-hlist-line-0",
                        "",
                        [
                            BoxUtil.labelBox(this._node as RepeatCondition, "until", "top-2-line-0-item-0"),
                            BoxUtil.getBoxOrAction(this._node as RepeatCondition, "until", "ScheduleExpression", this.mainHandler),
                        ],
                        { selectable: false },
                    ),
                    false,
                    BoxFactory.action(this._node, "optional-until", "until"),
                ),
            ],
            { selectable: false },
        );
    }
}
