// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory } from "@freon4dsl/core";
import { StaffRole } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type StaffRole.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class StaffRoleBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "StaffRole";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.verticalLayout(
            this._node as StaffRole,
            "StaffRole-overall",
            "",
            [
                BoxUtil.textBox(this._node as StaffRole, "name"),
                BoxUtil.getBoxOrAction(this._node as StaffRole, "description", "Description", this.mainHandler),
            ],
            { cssClass: "StaffRole" },
        );
    }

    private getParser(): Box {
        return BoxFactory.verticalLayout(
            this._node as StaffRole,
            "StaffRole-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as StaffRole,
                    "StaffRole-hlist-line-0",
                    "",
                    [
                        BoxUtil.labelBox(this._node as StaffRole, "Role:", "top-1-line-0-item-0"),
                        BoxUtil.textBox(this._node as StaffRole, "name"),
                    ],
                    { selectable: false },
                ),
                BoxUtil.getBoxOrAction(this._node as StaffRole, "description", "Description", this.mainHandler),
            ],
            { cssClass: "StaffRole" },
        );
    }
}
