// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory, FragmentBox } from "@freon4dsl/core";
import { StaffLevel } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type StaffLevel.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class StaffLevelBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "StaffLevel";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxUtil.fragmentWrapperBox(this._node as StaffLevel, "SingleLineItemComponent", this.getFragmentBox_staffLevelDetails(), {
            params: [
                { key: "cssClass", value: "type3" },
                { key: "canDelete", value: "true" },
                { key: "canAdd", value: "false" },
                { key: "canExpand", value: "true" },
                { key: "isExpanded", value: "true" },
                { key: "selectable", value: "true" },
                { key: "label", value: "# Staff" },
            ],
        });
    }

    private getParser(): Box {
        return BoxFactory.horizontalLayout(
            this._node as StaffLevel,
            "StaffLevel-hlist-line-0",
            "",
            [
                BoxUtil.textBox(this._node as StaffLevel, "staffAvailable"),
                BoxUtil.labelBox(this._node as StaffLevel, "on:", "top-1-line-0-item-1"),
                BoxUtil.getBoxOrAction(this._node as StaffLevel, "dateOrRange", "DateRange", this.mainHandler),
            ],
            { selectable: false },
        );
    }

    private getFragmentBox_staffLevelDetails(): FragmentBox {
        return new FragmentBox(
            this._node as StaffLevel,
            "StaffLevel-fragment-staffLevelDetails",
            BoxFactory.horizontalLayout(
                this._node as StaffLevel,
                "StaffLevel-fragment-staffLevelDetails-hlist-line-0",
                "",
                [
                    BoxUtil.textBox(this._node as StaffLevel, "staffAvailable"),
                    BoxUtil.labelBox(this._node as StaffLevel, "on:", "top-1-line-0-item-1"),
                    BoxUtil.partReplacerBox(this._node as StaffLevel, "dateOrRange", "DateRangePickerComponent"),
                ],
                { selectable: false },
            ),
            { cssClass: "StaffLevel-fragment-staffLevelDetails" },
        );
    }
}
