// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory, FragmentBox } from "@freon4dsl/core";
import { SystemAccess } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type SystemAccess.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class SystemAccessBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "SystemAccess";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxUtil.fragmentWrapperBox(
            this._node as SystemAccess,
            "SelectableListItemComponent",
            this.getFragmentBox_systemAccessDetails(),
            {
                params: [
                    { key: "cssClass", value: "type3" },
                    { key: "canDelete", value: "true" },
                    { key: "hideDragHandle", value: "true" },
                ],
            },
        );
    }

    private getParser(): Box {
        return BoxFactory.verticalLayout(
            this._node as SystemAccess,
            "SystemAccess-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as SystemAccess,
                    "SystemAccess-hlist-line-0",
                    "",
                    [
                        BoxUtil.labelBox(this._node as SystemAccess, "System Name:", "top-1-line-0-item-0"),
                        BoxUtil.textBox(this._node as SystemAccess, "name"),
                    ],
                    { selectable: false },
                ),
                BoxFactory.horizontalLayout(
                    this._node as SystemAccess,
                    "SystemAccess-hlist-line-1",
                    "",
                    [
                        BoxUtil.labelBox(this._node as SystemAccess, "Accessed At:", "top-1-line-1-item-0"),
                        BoxUtil.getBoxOrAction(this._node as SystemAccess, "accessedAt", "AccessedAt", this.mainHandler),
                    ],
                    { selectable: false },
                ),
                BoxUtil.getBoxOrAction(this._node as SystemAccess, "description", "Description", this.mainHandler),
            ],
            { cssClass: "SystemAccess" },
        );
    }

    private getFragmentBox_systemAccessDetails(): FragmentBox {
        return new FragmentBox(
            this._node as SystemAccess,
            "SystemAccess-fragment-systemAccessDetails",
            BoxFactory.verticalLayout(
                this._node as SystemAccess,
                "SystemAccess-fragment-systemAccessDetails-overall",
                "",
                [
                    BoxFactory.horizontalLayout(
                        this._node as SystemAccess,
                        "SystemAccess-fragment-systemAccessDetails-hlist-line-0",
                        "",
                        [
                            BoxUtil.labelBox(this._node as SystemAccess, "System:", "top-1-line-0-item-0"),
                            BoxUtil.textBox(this._node as SystemAccess, "name"),
                            BoxUtil.partReplacerBox(this._node as SystemAccess, "accessedAt", "CustomActionsComponent", {
                                params: [{ key: "placeholder", value: "accessed at" }],
                            }),
                        ],
                        { selectable: false },
                    ),
                    BoxUtil.getBoxOrAction(this._node as SystemAccess, "description", "Description", this.mainHandler),
                ],
                { cssClass: "SystemAccess-fragment-systemAccessDetails" },
            ),
            { cssClass: "SystemAccess-fragment-systemAccessDetails" },
        );
    }
}
