// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import {
    Box,
    BoxUtil,
    FreBoxProvider,
    FreProjectionHandler,
    FreNodeReference,
    type FreNamedNode,
    FragmentBox,
    BoxFactory,
} from "@freon4dsl/core";
import { SystemAccessReference, SystemAccess } from "../language/index.js";

import { LanguageEnvironment } from "../index.js";

/**
 * This class implements the box provider for a single node of type SystemAccessReference.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class SystemAccessReferenceBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "SystemAccessReference";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxUtil.fragmentWrapperBox(
            this._node as SystemAccessReference,
            "ReferenceComponent",
            this.getFragmentBox_systemAccessReferenceDetails(),
            {
                params: [
                    { key: "cssClass", value: "type3" },
                    { key: "canDelete", value: "true" },
                    { key: "canAdd", value: "false" },
                    { key: "canExpand", value: "false" },
                    { key: "isExpanded", value: "false" },
                    { key: "selectable", value: "true" },
                    { key: "label", value: "System" },
                    { key: "hideDragHandle", value: "true" },
                ],
            },
        );
    }

    private getParser(): Box {
        return BoxFactory.horizontalLayout(
            this._node as SystemAccessReference,
            "SystemAccessReference-hlist-line-0",
            "",
            [
                BoxUtil.labelBox(this._node as SystemAccessReference, "SystemAccessReference:", "top-1-line-0-item-0"),
                BoxUtil.referenceBox(
                    this._node as SystemAccessReference,
                    "system",
                    (selected: string | FreNamedNode) => {
                        const ref =
                            typeof selected === "string"
                                ? FreNodeReference.create<SystemAccess>(selected, "SystemAccess")
                                : FreNodeReference.create<SystemAccess>(selected as SystemAccess, "SystemAccess");
                        (this._node as SystemAccessReference).system = ref;
                    },
                    LanguageEnvironment.getInstance().scoper,
                ),
            ],
            { selectable: false },
        );
    }

    private getFragmentBox_systemAccessReferenceDetails(): FragmentBox {
        return new FragmentBox(
            this._node as SystemAccessReference,
            "SystemAccessReference-fragment-systemAccessReferenceDetails",
            BoxUtil.referenceBox(
                this._node as SystemAccessReference,
                "system",
                (selected: string | FreNamedNode) => {
                    const ref =
                        typeof selected === "string"
                            ? FreNodeReference.create<SystemAccess>(selected, "SystemAccess")
                            : FreNodeReference.create<SystemAccess>(selected as SystemAccess, "SystemAccess");
                    (this._node as SystemAccessReference).system = ref;
                },
                LanguageEnvironment.getInstance().scoper,
            ),
            { cssClass: "SystemAccessReference-fragment-systemAccessReferenceDetails" },
        );
    }
}
