// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory, FragmentBox, FreListInfo } from "@freon4dsl/core";
import { Task } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type Task.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class TaskBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser", "stepsShow"];
        this.knownTableProjections = ["default"];
        this.conceptName = "Task";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            } else if (projectionName === "stepsShow") {
                return this.getStepsShow();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxUtil.fragmentWrapperBox(this._node as Task, "ItemGroupComponent", this.getFragmentBox_taskDetails(), {
            params: [
                { key: "cssClass", value: "type4" },
                { key: "canDelete", value: "true" },
                { key: "canAdd", value: "false" },
                { key: "canExpand", value: "true" },
                { key: "isExpanded", value: "true" },
                { key: "selectable", value: "false" },
                { key: "label", value: "Task" },
            ],
        });
    }

    private getParser(): Box {
        return BoxFactory.verticalLayout(
            this._node as Task,
            "Task-overall",
            "",
            [
                BoxFactory.horizontalLayout(
                    this._node as Task,
                    "Task-hlist-line-0",
                    "",
                    [BoxUtil.labelBox(this._node as Task, "Task:", "top-1-line-0-item-0"), BoxUtil.textBox(this._node as Task, "name")],
                    { selectable: false },
                ),
                BoxUtil.getBoxOrAction(this._node as Task, "description", "Description", this.mainHandler),
                BoxUtil.labelBox(this._node as Task, "Steps:", "top-1-line-2-item-0"),
                BoxUtil.indentBox(
                    this._node as Task,
                    2,
                    "3",
                    BoxUtil.verticalPartListBox(
                        this._node as Task,
                        (this._node as Task).steps,
                        "steps",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
            ],
            { cssClass: "Task" },
        );
    }

    private getStepsShow(): Box {
        return BoxUtil.fragmentWrapperBox(this._node as Task, "ItemGroupComponent", this.getFragmentBox_taskDetailsWithSteps(), {
            params: [
                { key: "cssClass", value: "type4" },
                { key: "canDelete", value: "true" },
                { key: "canAdd", value: "false" },
                { key: "canExpand", value: "true" },
                { key: "isExpanded", value: "true" },
                { key: "selectable", value: "false" },
                { key: "label", value: "Task" },
            ],
        });
    }

    private getFragmentBox_taskDetails(): FragmentBox {
        return new FragmentBox(
            this._node as Task,
            "Task-fragment-taskDetails",
            BoxFactory.verticalLayout(
                this._node as Task,
                "Task-fragment-taskDetails-overall",
                "",
                [
                    BoxUtil.textBox(this._node as Task, "name"),
                    BoxUtil.getBoxOrAction(this._node as Task, "description", "Description", this.mainHandler),
                ],
                { cssClass: "Task-fragment-taskDetails" },
            ),
            { cssClass: "Task-fragment-taskDetails" },
        );
    }

    private getFragmentBox_taskDetailsWithSteps(): FragmentBox {
        return new FragmentBox(
            this._node as Task,
            "Task-fragment-taskDetailsWithSteps",
            BoxFactory.verticalLayout(
                this._node as Task,
                "Task-fragment-taskDetailsWithSteps-overall",
                "",
                [
                    BoxUtil.textBox(this._node as Task, "name"),
                    BoxUtil.getBoxOrAction(this._node as Task, "description", "Description", this.mainHandler),
                    BoxUtil.partListWrapperBox(
                        this._node as Task,
                        "steps",
                        "ListGroupComponent",
                        BoxUtil.verticalPartListBox(
                            this._node as Task,
                            (this._node as Task).steps,
                            "steps",
                            FreListInfo.NullListInfo,
                            this.mainHandler,
                        ),
                        {
                            params: [
                                { key: "cssClass", value: "type4" },
                                { key: "canAdd", value: "true" },
                                { key: "canDelete", value: "true" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "true" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Steps" },
                            ],
                        },
                    ),
                ],
                { cssClass: "Task-fragment-taskDetailsWithSteps" },
            ),
            { cssClass: "Task-fragment-taskDetailsWithSteps" },
        );
    }
}
