// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory } from "@freon4dsl/core";
import { When } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type When.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class WhenBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "When";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.horizontalLayout(
            this._node as When,
            "When-hlist-line-0",
            "",
            [
                BoxUtil.labelBox(this._node as When, "when", "top-1-line-0-item-0"),
                BoxUtil.partReplacerBox(this._node as When, "startWhen", "CustomActionsComponent", {
                    params: [{ key: "placeholder", value: "event reference" }],
                }),
                ,
                BoxUtil.partReplacerBox(this._node as When, "timeAmountPart", "CustomActionsComponent", {
                    params: [{ key: "placeholder", value: "time amount part" }],
                }),
            ],
            { selectable: false },
        );
    }

    private getParser(): Box {
        return BoxFactory.horizontalLayout(
            this._node as When,
            "When-hlist-line-0",
            "",
            [
                BoxUtil.labelBox(this._node as When, "when", "top-1-line-0-item-0"),
                BoxUtil.getBoxOrAction(this._node as When, "startWhen", "EventReference", this.mainHandler),
                BoxUtil.getBoxOrAction(this._node as When, "timeAmountPart", "TimeAmountPart", this.mainHandler),
            ],
            { selectable: false },
        );
    }
}
