// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generate(...)

import { type FreProjection, type FreCombinedActions, type FreTyper, type FreStdlib, type FreScoper } from "@freon4dsl/core";

import { CustomStudyExtractModelActions, CustomStudyExtractModelProjection } from "../editor/index.js";
import { CustomStudyExtractModelScoper } from "../scoper/index.js";
import { CustomStudyExtractModelTyperPart } from "../typer/CustomStudyExtractModelTyperPart.js";
import { CustomStudyExtractModelValidator } from "../validator/index.js";
import { CustomStudyExtractModelStdlib } from "../stdlib/CustomStudyExtractModelStdlib.js";
import { type StudyExtractModelCheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomStudyExtractModelProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomStudyExtractModelActions()];
    // add your custom validations here
    customValidations: StudyExtractModelCheckerInterface[] = [new CustomStudyExtractModelValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomStudyExtractModelScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomStudyExtractModelTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomStudyExtractModelStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
