// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generate(...)

import { type FreProjection, type FreCombinedActions, type FreTyper, type FreStdlib, type FreScoper } from "@freon4dsl/core";

import { CustomProjectConfigurationModelActions, CustomProjectConfigurationModelProjection } from "../editor/index.js";
import { CustomProjectConfigurationModelScoper } from "../scoper/index.js";
import { CustomProjectConfigurationModelTyperPart } from "../typer/CustomProjectConfigurationModelTyperPart.js";
import { CustomProjectConfigurationModelValidator } from "../validator/index.js";
import { CustomProjectConfigurationModelStdlib } from "../stdlib/CustomProjectConfigurationModelStdlib.js";
import { type ProjectConfigurationModelCheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomProjectConfigurationModelProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomProjectConfigurationModelActions()];
    // add your custom validations here
    customValidations: ProjectConfigurationModelCheckerInterface[] = [new CustomProjectConfigurationModelValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomProjectConfigurationModelScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomProjectConfigurationModelTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomProjectConfigurationModelStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
