// Generated by the Freon Language Generator.
// TEMPLATE: NamespaceCheckerTemplate.generateChecker(...)

import {
    FreError,
    FreErrorSeverity,
    type FreWriter,
    FreLanguageEnvironment,
    FreLanguage,
    FreNamespace,
    type FreNode,
    type FreNamedNode,
    notNullOrUndefined,
} from "@freon4dsl/core";
import {
    StudyConfigurationModel,
    Availability,
    PatientInfo,
    PatientHistoryUnit,
    StudyConfiguration,
    ScheduleExpression,
    EventReferenceExpression,
    PeriodReferenceExpression,
    Time,
    PreviousVisit,
    StartDay,
    CountExpression,
    LiteralExpression,
    String,
    NumberLiteralExpression,
    BinaryExpression,
    MultiplyExpression,
    PlusExpression,
    MinusExpression,
    DivideExpression,
    AndExpression,
    OrExpression,
    ComparisonExpression,
    LessThenExpression,
    GreaterThenExpression,
    EqualsExpression,
    TimeExpression,
    PatientHistory,
    PatientVisitStatus,
    PatientVisit,
    PatientNotAvailable,
    StaffLevel,
    Month,
    VisitDate,
    DateRange,
    DateConcept,
    EventSchedule,
    EventReference,
    TimeUnit,
    PhaseState,
    EventState,
    SimpleOperators,
    Days,
    TimeAmount,
    TimeAmountPart,
    Day,
    When,
    StudyStart,
    FirstDayOfStudy,
    Baseline,
    Previous,
    Unscheduled,
    AnyDay,
    EventWindow,
    ComplianceWindow,
    ComplianceWindowOf,
    StartingBy,
    EndingBy,
    BetweenTimes,
    RepeatCondition,
    Daily,
    Weekly,
    Monthly,
    Forever,
    RepeatEvery,
    RepeatCount,
    Period,
    TypeOfEvent,
    Event,
    AbstractTask,
    EventTask,
    Task,
    SharedTask,
    TaskReference,
    Step,
    WorkflowDescription,
    WorkflowBranch,
    Description,
    AbstractSystemAccess,
    SystemAccess,
    SystemAccessReference,
    AccessedAtURL,
    AccessedAPhoneNumber,
    StaffRole,
    AbstractPerson,
    PersonReference,
    Person,
    Reference,
    RobotMapping,
    SourceToTargetMapping,
} from "../language/index.js";

import { StudyConfigurationModelDefaultWorker } from "../utils/index.js";
import { type StudyConfigurationModelCheckerInterface } from "./StudyConfigurationModelValidator.js";

/**
 * Class StudyConfigurationModelNamespaceChecker is part of the implementation of the default validator.
 * It checks whether namespaces, as such defined in the .scope definition, have more than one node
 * with the same name.
 * Class StudyConfigurationModelWalker implements the traversal of the model tree. This class implements
 * the actual checking of each node in the tree.
 */
export class StudyConfigurationModelNamespaceChecker
    extends StudyConfigurationModelDefaultWorker
    implements StudyConfigurationModelCheckerInterface
{
    // 'myWriter' is used to provide error messages on the nodes in the model tree
    myWriter: FreWriter = FreLanguageEnvironment.getInstance().writer;
    // 'errorList' holds the errors found while traversing the model tree
    errorList: FreError[] = [];

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStudyConfigurationModel(node: StudyConfigurationModel): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StudyConfigurationModel")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAvailability(node: Availability): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Availability")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePatientInfo(node: PatientInfo): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PatientInfo")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePatientHistoryUnit(node: PatientHistoryUnit): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PatientHistoryUnit")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStudyConfiguration(node: StudyConfiguration): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StudyConfiguration")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeScheduleExpression(node: ScheduleExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("ScheduleExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEventReferenceExpression(node: EventReferenceExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EventReferenceExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePeriodReferenceExpression(node: PeriodReferenceExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PeriodReferenceExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTime(node: Time): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Time")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePreviousVisit(node: PreviousVisit): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PreviousVisit")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStartDay(node: StartDay): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StartDay")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeCountExpression(node: CountExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("CountExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeLiteralExpression(node: LiteralExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("LiteralExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeString(node: String): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("String")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeNumberLiteralExpression(node: NumberLiteralExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("NumberLiteralExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeBinaryExpression(node: BinaryExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("BinaryExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeMultiplyExpression(node: MultiplyExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("MultiplyExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePlusExpression(node: PlusExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PlusExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeMinusExpression(node: MinusExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("MinusExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDivideExpression(node: DivideExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("DivideExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAndExpression(node: AndExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AndExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeOrExpression(node: OrExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("OrExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeComparisonExpression(node: ComparisonExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("ComparisonExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeLessThenExpression(node: LessThenExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("LessThenExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeGreaterThenExpression(node: GreaterThenExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("GreaterThenExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEqualsExpression(node: EqualsExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EqualsExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTimeExpression(node: TimeExpression): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("TimeExpression")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePatientHistory(node: PatientHistory): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PatientHistory")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePatientVisitStatus(node: PatientVisitStatus): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PatientVisitStatus")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePatientVisit(node: PatientVisit): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PatientVisit")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePatientNotAvailable(node: PatientNotAvailable): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PatientNotAvailable")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStaffLevel(node: StaffLevel): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StaffLevel")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeMonth(node: Month): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Month")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeVisitDate(node: VisitDate): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("VisitDate")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDateRange(node: DateRange): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("DateRange")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDateConcept(node: DateConcept): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("DateConcept")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEventSchedule(node: EventSchedule): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EventSchedule")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEventReference(node: EventReference): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EventReference")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTimeUnit(node: TimeUnit): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("TimeUnit")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePhaseState(node: PhaseState): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PhaseState")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEventState(node: EventState): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EventState")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeSimpleOperators(node: SimpleOperators): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("SimpleOperators")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDays(node: Days): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Days")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTimeAmount(node: TimeAmount): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("TimeAmount")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTimeAmountPart(node: TimeAmountPart): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("TimeAmountPart")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDay(node: Day): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Day")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeWhen(node: When): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("When")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStudyStart(node: StudyStart): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StudyStart")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeFirstDayOfStudy(node: FirstDayOfStudy): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("FirstDayOfStudy")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeBaseline(node: Baseline): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Baseline")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePrevious(node: Previous): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Previous")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeUnscheduled(node: Unscheduled): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Unscheduled")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAnyDay(node: AnyDay): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AnyDay")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEventWindow(node: EventWindow): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EventWindow")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeComplianceWindow(node: ComplianceWindow): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("ComplianceWindow")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeComplianceWindowOf(node: ComplianceWindowOf): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("ComplianceWindowOf")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStartingBy(node: StartingBy): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StartingBy")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEndingBy(node: EndingBy): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EndingBy")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeBetweenTimes(node: BetweenTimes): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("BetweenTimes")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeRepeatCondition(node: RepeatCondition): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("RepeatCondition")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDaily(node: Daily): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Daily")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeWeekly(node: Weekly): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Weekly")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeMonthly(node: Monthly): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Monthly")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeForever(node: Forever): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Forever")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeRepeatEvery(node: RepeatEvery): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("RepeatEvery")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeRepeatCount(node: RepeatCount): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("RepeatCount")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePeriod(node: Period): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Period")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTypeOfEvent(node: TypeOfEvent): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("TypeOfEvent")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEvent(node: Event): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Event")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAbstractTask(node: AbstractTask): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AbstractTask")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeEventTask(node: EventTask): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("EventTask")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTask(node: Task): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Task")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeSharedTask(node: SharedTask): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("SharedTask")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeTaskReference(node: TaskReference): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("TaskReference")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStep(node: Step): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Step")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeWorkflowDescription(node: WorkflowDescription): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("WorkflowDescription")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeWorkflowBranch(node: WorkflowBranch): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("WorkflowBranch")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeDescription(node: Description): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Description")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAbstractSystemAccess(node: AbstractSystemAccess): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AbstractSystemAccess")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeSystemAccess(node: SystemAccess): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("SystemAccess")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeSystemAccessReference(node: SystemAccessReference): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("SystemAccessReference")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAccessedAtURL(node: AccessedAtURL): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AccessedAtURL")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAccessedAPhoneNumber(node: AccessedAPhoneNumber): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AccessedAPhoneNumber")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeStaffRole(node: StaffRole): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("StaffRole")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeAbstractPerson(node: AbstractPerson): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("AbstractPerson")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePersonReference(node: PersonReference): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("PersonReference")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforePerson(node: Person): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Person")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeReference(node: Reference): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("Reference")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeRobotMapping(node: RobotMapping): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("RobotMapping")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    /**
     * Checks 'node' before checking its children.
     * Found errors are pushed onto 'errorList'.
     * If an error is found, it is NOT considered 'fatal', which means that other checks on
     * 'node' are performed.
     *
     * @param node
     */
    public execBeforeSourceToTargetMapping(node: SourceToTargetMapping): boolean {
        if (notNullOrUndefined(node) && FreLanguage.getInstance().classifier("SourceToTargetMapping")?.isNamespace) {
            this.checkDuplicateNamesInNamespace(node);
        }
        return false;
    }

    private checkDuplicateNamesInNamespace(node: FreNode) {
        const declaredNodes: Set<FreNamedNode> = FreNamespace.create(node).getDeclaredNodes(false);
        const declaredNames: string[] = [];
        const doubleNames: string[] = [];
        declaredNodes.forEach((nn) => {
            if (declaredNames.indexOf(nn.name) > -1) {
                doubleNames.push(nn.name);
            } else {
                declaredNames.push(nn.name);
            }
        });
        if (doubleNames.length > 0) {
            const namespaceName: string = "name" in node ? (node as FreNamedNode).name : "<unnamed>";
            this.errorList.push(
                new FreError(
                    `Namespace ${namespaceName} has multiple nodes with the same name [${doubleNames.map((n) => n).join(", ")}].`,
                    node,
                    "name",
                    FreErrorSeverity.Error,
                ),
            );
        }
    }
}
