// Generated by the Freon Language Generator.
import { FreProjection, FreCombinedActions, FreTyper, FreStdlib, FreScoper } from "@freon4dsl/core";
import { CustomOctopusModelActions, CustomOctopusModelProjection } from "../editor/index.js";
import { CustomOctopusModelScoper } from "../scoper/index.js";
import { CustomOctopusModelTyperPart } from "../typer/index.js";
import { CustomOctopusModelValidator } from "../validator/index.js";
import { CustomOctopusModelStdlib } from "../stdlib/index.js";
import { OctopusModelCheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomOctopusModelProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomOctopusModelActions()];
    // add your custom validations here
    customValidations: OctopusModelCheckerInterface[] = [new CustomOctopusModelValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomOctopusModelScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomOctopusModelTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomOctopusModelStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
