// Generated by the Freon Language Generator.
// TEMPLATE: InterpreterBaseTemplate.interpreterInit(...)
// Will be overwritten with every generation.

import {
    type ConceptFunction,
    type FreInterpreter,
    type IMainInterpreter,
    InterpreterContext,
    InterpreterTracer,
    MainInterpreter,
    type OwningPropertyFunction,
    type FreNode,
    RtObject,
    RtError,
} from "@freon4dsl/core";

import { QnameModelInterpreterInit } from "../freon/interpreter/QnameModelInterpreterInit.js";

const getPropertyFunction: OwningPropertyFunction = (node: Object) => {
    const index = (node as FreNode).freOwnerDescriptor().propertyIndex;
    return (node as FreNode).freOwnerDescriptor().propertyName + (index !== undefined ? "[" + index + "]" : "");
};

/**
 * Function that returns the concept name for `node`.
 * Used by the interpreter to find which evaluator should be use for each node.
 */
const getConceptFunction: ConceptFunction = (node: Object) => {
    if (node === undefined) {
        return "";
    }
    return (node as FreNode).freLanguageConcept();
};

/**
 * The facade around the actual interpreter to avoid improper usage.
 * Sets the functions used to access the expression tree.
 * Ensures all internal interpreter state is cleaned when creating a new instance.
 */
export class MainQnameModelInterpreter implements FreInterpreter {
    private static main: IMainInterpreter | null = null;

    constructor() {
        MainQnameModelInterpreter.getMain();
    }

    private static getMain(): IMainInterpreter {
        return (this.main ??= MainInterpreter.instance(QnameModelInterpreterInit, getConceptFunction, getPropertyFunction));
    }

    setTracing(value: boolean) {
        MainQnameModelInterpreter.getMain().setTracing(value);
    }

    getTrace(): InterpreterTracer {
        return MainQnameModelInterpreter.getMain().getTrace();
    }

    evaluate(node: Object): RtObject {
        return this.evaluateWithContext(node, InterpreterContext.EMPTY_CONTEXT);
    }

    evaluateWithContext(node: Object, ctx: InterpreterContext): RtObject {
        MainQnameModelInterpreter.getMain().reset();
        try {
            return MainQnameModelInterpreter.getMain().evaluate(node, ctx);
        } catch (e: any) {
            return new RtError(e.message);
        }
    }
}
