// Generated by the Freon Language Generator.
export { ConformanceRulesModelEnvironment as LanguageEnvironment } from "./config/gen/ConformanceRulesModelEnvironment.js";
export * from "./language/gen/index.js";
