// Generated by the Freon Language Generator.
// TEMPLATE: WalkerTemplate.generateWalker(...)

import { FreLogger, type FreNode, notNullOrUndefined } from "@freon4dsl/core";
import {
    EqualsExpression,
    GreaterThenExpression,
    LessThenExpression,
    TaskReference,
    Task,
    ComparisonExpression,
    OrExpression,
    AndExpression,
    DivideExpression,
    MinusExpression,
    PlusExpression,
    MultiplyExpression,
    NumberLiteralExpression,
    Person,
    PersonReference,
    SystemAccessReference,
    SystemAccess,
    SharedTask,
    EventTask,
    ComplianceWindowOf,
    AnyDay,
    Baseline,
    BinaryExpression,
    LiteralExpression,
    CountExpression,
    StartDay,
    PreviousVisit,
    Time,
    PeriodReferenceExpression,
    EventReferenceExpression,
    SourceToTargetMapping,
    RobotMapping,
    Reference,
    AbstractPerson,
    StaffRole,
    AccessedAPhoneNumber,
    AccessedAtURL,
    AbstractSystemAccess,
    Description,
    WorkflowBranch,
    WorkflowDescription,
    Step,
    AbstractTask,
    Event,
    TypeOfEvent,
    Period,
    RepeatCount,
    RepeatEvery,
    Forever,
    Monthly,
    Weekly,
    Daily,
    RepeatCondition,
    BetweenTimes,
    EndingBy,
    StartingBy,
    ComplianceWindow,
    EventWindow,
    Unscheduled,
    Previous,
    FirstDayOfStudy,
    StudyStart,
    When,
    Day,
    TimeAmountPart,
    TimeAmount,
    Days,
    SimpleOperators,
    EventState,
    PhaseState,
    TimeUnit,
    EventReference,
    EventSchedule,
    DateConcept,
    DateRange,
    VisitDate,
    Month,
    StaffLevel,
    PatientNotAvailable,
    PatientVisit,
    PatientVisitStatus,
    PatientHistory,
    TimeExpression,
    String,
    ScheduleExpression,
    Availability,
    PatientInfo,
    PatientHistoryUnit,
    StudyConfiguration,
    StudyConfigurationModel,
} from "../language/index.js";

import { type StudyConfigurationModelWorker } from "./StudyConfigurationModelWorker.js";

const LOGGER = new FreLogger("StudyConfigurationModelWalker");

/**
 * Class StudyConfigurationModelWalker implements the extended visitor pattern of instances of language StudyConfigurationModel.
 * This class implements the traversal of the model tree, classes that implement StudyConfigurationModelWorker
 * are responsible for the actual work being done on the nodes of the tree.
 * Every node is visited twice, once before the visit of its children, and once after this visit.
 *
 * With the use of the parameter 'includeChildren', which takes a function, a very fine-grained control can be taken
 * over which nodes are and are not visited.
 */
export class StudyConfigurationModelWalker {
    myWorkers: StudyConfigurationModelWorker[] = []; // the instances that do the actual work on each node of the tree

    /**
     * This method is the entry point of the traversal through the model tree. Each of the workers will be called in
     * the order in which they are present in the array 'myWorkers'. If, for a tree node, a worker returns 'false',
     * none of the rest of the workers will be called. For that particular node both the 'execBefore' and 'execAfter'
     * method of any of the other workers will be skipped.
     *
     * @param node the top node of the part of the tree to be visited
     * @param includeChildren if true, the children of 'node' will also be visited
     */
    public walk(node: FreNode, includeChildren?: (elem: FreNode) => boolean) {
        if (this.myWorkers.length > 0) {
            if (node instanceof EqualsExpression) {
                return this.walkEqualsExpression(node, includeChildren);
            }
            if (node instanceof GreaterThenExpression) {
                return this.walkGreaterThenExpression(node, includeChildren);
            }
            if (node instanceof LessThenExpression) {
                return this.walkLessThenExpression(node, includeChildren);
            }
            if (node instanceof TaskReference) {
                return this.walkTaskReference(node, includeChildren);
            }
            if (node instanceof Task) {
                return this.walkTask(node, includeChildren);
            }
            if (node instanceof ComparisonExpression) {
                return this.walkComparisonExpression(node, includeChildren);
            }
            if (node instanceof OrExpression) {
                return this.walkOrExpression(node, includeChildren);
            }
            if (node instanceof AndExpression) {
                return this.walkAndExpression(node, includeChildren);
            }
            if (node instanceof DivideExpression) {
                return this.walkDivideExpression(node, includeChildren);
            }
            if (node instanceof MinusExpression) {
                return this.walkMinusExpression(node, includeChildren);
            }
            if (node instanceof PlusExpression) {
                return this.walkPlusExpression(node, includeChildren);
            }
            if (node instanceof MultiplyExpression) {
                return this.walkMultiplyExpression(node, includeChildren);
            }
            if (node instanceof NumberLiteralExpression) {
                return this.walkNumberLiteralExpression(node, includeChildren);
            }
            if (node instanceof Person) {
                return this.walkPerson(node, includeChildren);
            }
            if (node instanceof PersonReference) {
                return this.walkPersonReference(node, includeChildren);
            }
            if (node instanceof SystemAccessReference) {
                return this.walkSystemAccessReference(node, includeChildren);
            }
            if (node instanceof SystemAccess) {
                return this.walkSystemAccess(node, includeChildren);
            }
            if (node instanceof SharedTask) {
                return this.walkSharedTask(node, includeChildren);
            }
            if (node instanceof EventTask) {
                return this.walkEventTask(node, includeChildren);
            }
            if (node instanceof ComplianceWindowOf) {
                return this.walkComplianceWindowOf(node, includeChildren);
            }
            if (node instanceof AnyDay) {
                return this.walkAnyDay(node, includeChildren);
            }
            if (node instanceof Baseline) {
                return this.walkBaseline(node, includeChildren);
            }
            if (node instanceof BinaryExpression) {
                return this.walkBinaryExpression(node, includeChildren);
            }
            if (node instanceof LiteralExpression) {
                return this.walkLiteralExpression(node, includeChildren);
            }
            if (node instanceof CountExpression) {
                return this.walkCountExpression(node, includeChildren);
            }
            if (node instanceof StartDay) {
                return this.walkStartDay(node, includeChildren);
            }
            if (node instanceof PreviousVisit) {
                return this.walkPreviousVisit(node, includeChildren);
            }
            if (node instanceof Time) {
                return this.walkTime(node, includeChildren);
            }
            if (node instanceof PeriodReferenceExpression) {
                return this.walkPeriodReferenceExpression(node, includeChildren);
            }
            if (node instanceof EventReferenceExpression) {
                return this.walkEventReferenceExpression(node, includeChildren);
            }
            if (node instanceof SourceToTargetMapping) {
                return this.walkSourceToTargetMapping(node, includeChildren);
            }
            if (node instanceof RobotMapping) {
                return this.walkRobotMapping(node, includeChildren);
            }
            if (node instanceof Reference) {
                return this.walkReference(node, includeChildren);
            }
            if (node instanceof AbstractPerson) {
                return this.walkAbstractPerson(node, includeChildren);
            }
            if (node instanceof StaffRole) {
                return this.walkStaffRole(node, includeChildren);
            }
            if (node instanceof AccessedAPhoneNumber) {
                return this.walkAccessedAPhoneNumber(node, includeChildren);
            }
            if (node instanceof AccessedAtURL) {
                return this.walkAccessedAtURL(node, includeChildren);
            }
            if (node instanceof AbstractSystemAccess) {
                return this.walkAbstractSystemAccess(node, includeChildren);
            }
            if (node instanceof Description) {
                return this.walkDescription(node, includeChildren);
            }
            if (node instanceof WorkflowBranch) {
                return this.walkWorkflowBranch(node, includeChildren);
            }
            if (node instanceof WorkflowDescription) {
                return this.walkWorkflowDescription(node, includeChildren);
            }
            if (node instanceof Step) {
                return this.walkStep(node, includeChildren);
            }
            if (node instanceof AbstractTask) {
                return this.walkAbstractTask(node, includeChildren);
            }
            if (node instanceof Event) {
                return this.walkEvent(node, includeChildren);
            }
            if (node instanceof TypeOfEvent) {
                return this.walkTypeOfEvent(node, includeChildren);
            }
            if (node instanceof Period) {
                return this.walkPeriod(node, includeChildren);
            }
            if (node instanceof RepeatCount) {
                return this.walkRepeatCount(node, includeChildren);
            }
            if (node instanceof RepeatEvery) {
                return this.walkRepeatEvery(node, includeChildren);
            }
            if (node instanceof Forever) {
                return this.walkForever(node, includeChildren);
            }
            if (node instanceof Monthly) {
                return this.walkMonthly(node, includeChildren);
            }
            if (node instanceof Weekly) {
                return this.walkWeekly(node, includeChildren);
            }
            if (node instanceof Daily) {
                return this.walkDaily(node, includeChildren);
            }
            if (node instanceof RepeatCondition) {
                return this.walkRepeatCondition(node, includeChildren);
            }
            if (node instanceof BetweenTimes) {
                return this.walkBetweenTimes(node, includeChildren);
            }
            if (node instanceof EndingBy) {
                return this.walkEndingBy(node, includeChildren);
            }
            if (node instanceof StartingBy) {
                return this.walkStartingBy(node, includeChildren);
            }
            if (node instanceof ComplianceWindow) {
                return this.walkComplianceWindow(node, includeChildren);
            }
            if (node instanceof EventWindow) {
                return this.walkEventWindow(node, includeChildren);
            }
            if (node instanceof Unscheduled) {
                return this.walkUnscheduled(node, includeChildren);
            }
            if (node instanceof Previous) {
                return this.walkPrevious(node, includeChildren);
            }
            if (node instanceof FirstDayOfStudy) {
                return this.walkFirstDayOfStudy(node, includeChildren);
            }
            if (node instanceof StudyStart) {
                return this.walkStudyStart(node, includeChildren);
            }
            if (node instanceof When) {
                return this.walkWhen(node, includeChildren);
            }
            if (node instanceof Day) {
                return this.walkDay(node, includeChildren);
            }
            if (node instanceof TimeAmountPart) {
                return this.walkTimeAmountPart(node, includeChildren);
            }
            if (node instanceof TimeAmount) {
                return this.walkTimeAmount(node, includeChildren);
            }
            if (node instanceof Days) {
                return this.walkDays(node, includeChildren);
            }
            if (node instanceof SimpleOperators) {
                return this.walkSimpleOperators(node, includeChildren);
            }
            if (node instanceof EventState) {
                return this.walkEventState(node, includeChildren);
            }
            if (node instanceof PhaseState) {
                return this.walkPhaseState(node, includeChildren);
            }
            if (node instanceof TimeUnit) {
                return this.walkTimeUnit(node, includeChildren);
            }
            if (node instanceof EventReference) {
                return this.walkEventReference(node, includeChildren);
            }
            if (node instanceof EventSchedule) {
                return this.walkEventSchedule(node, includeChildren);
            }
            if (node instanceof DateConcept) {
                return this.walkDateConcept(node, includeChildren);
            }
            if (node instanceof DateRange) {
                return this.walkDateRange(node, includeChildren);
            }
            if (node instanceof VisitDate) {
                return this.walkVisitDate(node, includeChildren);
            }
            if (node instanceof Month) {
                return this.walkMonth(node, includeChildren);
            }
            if (node instanceof StaffLevel) {
                return this.walkStaffLevel(node, includeChildren);
            }
            if (node instanceof PatientNotAvailable) {
                return this.walkPatientNotAvailable(node, includeChildren);
            }
            if (node instanceof PatientVisit) {
                return this.walkPatientVisit(node, includeChildren);
            }
            if (node instanceof PatientVisitStatus) {
                return this.walkPatientVisitStatus(node, includeChildren);
            }
            if (node instanceof PatientHistory) {
                return this.walkPatientHistory(node, includeChildren);
            }
            if (node instanceof TimeExpression) {
                return this.walkTimeExpression(node, includeChildren);
            }
            if (node instanceof String) {
                return this.walkString(node, includeChildren);
            }
            if (node instanceof ScheduleExpression) {
                return this.walkScheduleExpression(node, includeChildren);
            }
            if (node instanceof Availability) {
                return this.walkAvailability(node, includeChildren);
            }
            if (node instanceof PatientInfo) {
                return this.walkPatientInfo(node, includeChildren);
            }
            if (node instanceof PatientHistoryUnit) {
                return this.walkPatientHistoryUnit(node, includeChildren);
            }
            if (node instanceof StudyConfiguration) {
                return this.walkStudyConfiguration(node, includeChildren);
            }
            if (node instanceof StudyConfigurationModel) {
                return this.walkStudyConfigurationModel(node, includeChildren);
            }
        } else {
            LOGGER.error("No worker found.");
        }
    }

    private walkEqualsExpression(node: EqualsExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEqualsExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEqualsExpression(node);
            }
        }
    }

    private walkGreaterThenExpression(node: GreaterThenExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeGreaterThenExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterGreaterThenExpression(node);
            }
        }
    }

    private walkLessThenExpression(node: LessThenExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeLessThenExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterLessThenExpression(node);
            }
        }
    }

    private walkTaskReference(node: TaskReference, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTaskReference(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTaskReference(node);
            }
        }
    }

    private walkTask(node: Task, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTask(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }
        node.steps.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTask(node);
            }
        }
    }

    private walkComparisonExpression(node: ComparisonExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeComparisonExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterComparisonExpression(node);
            }
        }
    }

    private walkOrExpression(node: OrExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeOrExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterOrExpression(node);
            }
        }
    }

    private walkAndExpression(node: AndExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAndExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAndExpression(node);
            }
        }
    }

    private walkDivideExpression(node: DivideExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDivideExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDivideExpression(node);
            }
        }
    }

    private walkMinusExpression(node: MinusExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeMinusExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterMinusExpression(node);
            }
        }
    }

    private walkPlusExpression(node: PlusExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePlusExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPlusExpression(node);
            }
        }
    }

    private walkMultiplyExpression(node: MultiplyExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeMultiplyExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterMultiplyExpression(node);
            }
        }
    }

    private walkNumberLiteralExpression(node: NumberLiteralExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeNumberLiteralExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterNumberLiteralExpression(node);
            }
        }
    }

    private walkPerson(node: Person, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePerson(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPerson(node);
            }
        }
    }

    private walkPersonReference(node: PersonReference, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePersonReference(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPersonReference(node);
            }
        }
    }

    private walkSystemAccessReference(node: SystemAccessReference, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeSystemAccessReference(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterSystemAccessReference(node);
            }
        }
    }

    private walkSystemAccess(node: SystemAccess, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeSystemAccess(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.accessedAt) && includeChildren(node.accessedAt)) {
            this.walk(node.accessedAt, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterSystemAccess(node);
            }
        }
    }

    private walkSharedTask(node: SharedTask, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeSharedTask(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }
        node.steps.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterSharedTask(node);
            }
        }
    }

    private walkEventTask(node: EventTask, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEventTask(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEventTask(node);
            }
        }
    }

    private walkComplianceWindowOf(node: ComplianceWindowOf, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeComplianceWindowOf(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.maxDaysBefore) && includeChildren(node.maxDaysBefore)) {
            this.walk(node.maxDaysBefore, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.maxDaysAfter) && includeChildren(node.maxDaysAfter)) {
            this.walk(node.maxDaysAfter, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterComplianceWindowOf(node);
            }
        }
    }

    private walkAnyDay(node: AnyDay, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAnyDay(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAnyDay(node);
            }
        }
    }

    private walkBaseline(node: Baseline, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeBaseline(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterBaseline(node);
            }
        }
    }

    private walkBinaryExpression(node: BinaryExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeBinaryExpression(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.left) && includeChildren(node.left)) {
            this.walk(node.left, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.right) && includeChildren(node.right)) {
            this.walk(node.right, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterBinaryExpression(node);
            }
        }
    }

    private walkLiteralExpression(node: LiteralExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeLiteralExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterLiteralExpression(node);
            }
        }
    }

    private walkCountExpression(node: CountExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeCountExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterCountExpression(node);
            }
        }
    }

    private walkStartDay(node: StartDay, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStartDay(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStartDay(node);
            }
        }
    }

    private walkPreviousVisit(node: PreviousVisit, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePreviousVisit(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPreviousVisit(node);
            }
        }
    }

    private walkTime(node: Time, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTime(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTime(node);
            }
        }
    }

    private walkPeriodReferenceExpression(node: PeriodReferenceExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePeriodReferenceExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPeriodReferenceExpression(node);
            }
        }
    }

    private walkEventReferenceExpression(node: EventReferenceExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEventReferenceExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEventReferenceExpression(node);
            }
        }
    }

    private walkSourceToTargetMapping(node: SourceToTargetMapping, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeSourceToTargetMapping(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterSourceToTargetMapping(node);
            }
        }
    }

    private walkRobotMapping(node: RobotMapping, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeRobotMapping(node);
            }
        }
        // work on children in the model tree
        node.sourceToTargetMappings.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterRobotMapping(node);
            }
        }
    }

    private walkReference(node: Reference, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeReference(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterReference(node);
            }
        }
    }

    private walkAbstractPerson(node: AbstractPerson, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAbstractPerson(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAbstractPerson(node);
            }
        }
    }

    private walkStaffRole(node: StaffRole, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStaffRole(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStaffRole(node);
            }
        }
    }

    private walkAccessedAPhoneNumber(node: AccessedAPhoneNumber, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAccessedAPhoneNumber(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAccessedAPhoneNumber(node);
            }
        }
    }

    private walkAccessedAtURL(node: AccessedAtURL, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAccessedAtURL(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAccessedAtURL(node);
            }
        }
    }

    private walkAbstractSystemAccess(node: AbstractSystemAccess, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAbstractSystemAccess(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAbstractSystemAccess(node);
            }
        }
    }

    private walkDescription(node: Description, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDescription(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDescription(node);
            }
        }
    }

    private walkWorkflowBranch(node: WorkflowBranch, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeWorkflowBranch(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.branch) && includeChildren(node.branch)) {
            this.walk(node.branch, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterWorkflowBranch(node);
            }
        }
    }

    private walkWorkflowDescription(node: WorkflowDescription, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeWorkflowDescription(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.text) && includeChildren(node.text)) {
            this.walk(node.text, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterWorkflowDescription(node);
            }
        }
    }

    private walkStep(node: Step, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStep(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }
        node.references.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.people.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.systems.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStep(node);
            }
        }
    }

    private walkAbstractTask(node: AbstractTask, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAbstractTask(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAbstractTask(node);
            }
        }
    }

    private walkEvent(node: Event, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEvent(node);
            }
        }
        // work on children in the model tree
        node.tasks.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.schedule) && includeChildren(node.schedule)) {
            this.walk(node.schedule, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEvent(node);
            }
        }
    }

    private walkTypeOfEvent(node: TypeOfEvent, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTypeOfEvent(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTypeOfEvent(node);
            }
        }
    }

    private walkPeriod(node: Period, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePeriod(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }
        node.events.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPeriod(node);
            }
        }
    }

    private walkRepeatCount(node: RepeatCount, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeRepeatCount(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterRepeatCount(node);
            }
        }
    }

    private walkRepeatEvery(node: RepeatEvery, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeRepeatEvery(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.repeatEvery) && includeChildren(node.repeatEvery)) {
            this.walk(node.repeatEvery, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterRepeatEvery(node);
            }
        }
    }

    private walkForever(node: Forever, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeForever(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterForever(node);
            }
        }
    }

    private walkMonthly(node: Monthly, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeMonthly(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterMonthly(node);
            }
        }
    }

    private walkWeekly(node: Weekly, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeWeekly(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterWeekly(node);
            }
        }
    }

    private walkDaily(node: Daily, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDaily(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDaily(node);
            }
        }
    }

    private walkRepeatCondition(node: RepeatCondition, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeRepeatCondition(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.repeatUnit) && includeChildren(node.repeatUnit)) {
            this.walk(node.repeatUnit, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.until) && includeChildren(node.until)) {
            this.walk(node.until, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterRepeatCondition(node);
            }
        }
    }

    private walkBetweenTimes(node: BetweenTimes, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeBetweenTimes(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterBetweenTimes(node);
            }
        }
    }

    private walkEndingBy(node: EndingBy, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEndingBy(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEndingBy(node);
            }
        }
    }

    private walkStartingBy(node: StartingBy, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStartingBy(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStartingBy(node);
            }
        }
    }

    private walkComplianceWindow(node: ComplianceWindow, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeComplianceWindow(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterComplianceWindow(node);
            }
        }
    }

    private walkEventWindow(node: EventWindow, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEventWindow(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.daysBefore) && includeChildren(node.daysBefore)) {
            this.walk(node.daysBefore, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.daysAfter) && includeChildren(node.daysAfter)) {
            this.walk(node.daysAfter, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.complianceWindow) && includeChildren(node.complianceWindow)) {
            this.walk(node.complianceWindow, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEventWindow(node);
            }
        }
    }

    private walkUnscheduled(node: Unscheduled, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeUnscheduled(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterUnscheduled(node);
            }
        }
    }

    private walkPrevious(node: Previous, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePrevious(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPrevious(node);
            }
        }
    }

    private walkFirstDayOfStudy(node: FirstDayOfStudy, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeFirstDayOfStudy(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterFirstDayOfStudy(node);
            }
        }
    }

    private walkStudyStart(node: StudyStart, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStudyStart(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStudyStart(node);
            }
        }
    }

    private walkWhen(node: When, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeWhen(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.startWhen) && includeChildren(node.startWhen)) {
            this.walk(node.startWhen, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterWhen(node);
            }
        }
    }

    private walkDay(node: Day, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDay(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmountPart) && includeChildren(node.timeAmountPart)) {
            this.walk(node.timeAmountPart, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDay(node);
            }
        }
    }

    private walkTimeAmountPart(node: TimeAmountPart, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTimeAmountPart(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.timeAmount) && includeChildren(node.timeAmount)) {
            this.walk(node.timeAmount, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTimeAmountPart(node);
            }
        }
    }

    private walkTimeAmount(node: TimeAmount, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTimeAmount(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTimeAmount(node);
            }
        }
    }

    private walkDays(node: Days, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDays(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDays(node);
            }
        }
    }

    private walkSimpleOperators(node: SimpleOperators, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeSimpleOperators(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterSimpleOperators(node);
            }
        }
    }

    private walkEventState(node: EventState, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEventState(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEventState(node);
            }
        }
    }

    private walkPhaseState(node: PhaseState, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePhaseState(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPhaseState(node);
            }
        }
    }

    private walkTimeUnit(node: TimeUnit, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTimeUnit(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTimeUnit(node);
            }
        }
    }

    private walkEventReference(node: EventReference, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEventReference(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEventReference(node);
            }
        }
    }

    private walkEventSchedule(node: EventSchedule, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeEventSchedule(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.eventStart) && includeChildren(node.eventStart)) {
            this.walk(node.eventStart, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.eventWindow) && includeChildren(node.eventWindow)) {
            this.walk(node.eventWindow, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.eventRepeat) && includeChildren(node.eventRepeat)) {
            this.walk(node.eventRepeat, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.eventTimeOfDay) && includeChildren(node.eventTimeOfDay)) {
            this.walk(node.eventTimeOfDay, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterEventSchedule(node);
            }
        }
    }

    private walkDateConcept(node: DateConcept, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDateConcept(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDateConcept(node);
            }
        }
    }

    private walkDateRange(node: DateRange, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeDateRange(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.startDate) && includeChildren(node.startDate)) {
            this.walk(node.startDate, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.endDate) && includeChildren(node.endDate)) {
            this.walk(node.endDate, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterDateRange(node);
            }
        }
    }

    private walkVisitDate(node: VisitDate, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeVisitDate(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterVisitDate(node);
            }
        }
    }

    private walkMonth(node: Month, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeMonth(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterMonth(node);
            }
        }
    }

    private walkStaffLevel(node: StaffLevel, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStaffLevel(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.startDate) && includeChildren(node.startDate)) {
            this.walk(node.startDate, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.endDate) && includeChildren(node.endDate)) {
            this.walk(node.endDate, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.dateOrRange) && includeChildren(node.dateOrRange)) {
            this.walk(node.dateOrRange, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStaffLevel(node);
            }
        }
    }

    private walkPatientNotAvailable(node: PatientNotAvailable, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePatientNotAvailable(node);
            }
        }
        // work on children in the model tree
        node.dates.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPatientNotAvailable(node);
            }
        }
    }

    private walkPatientVisit(node: PatientVisit, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePatientVisit(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.actualVisitDate) && includeChildren(node.actualVisitDate)) {
            this.walk(node.actualVisitDate, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPatientVisit(node);
            }
        }
    }

    private walkPatientVisitStatus(node: PatientVisitStatus, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePatientVisitStatus(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPatientVisitStatus(node);
            }
        }
    }

    private walkPatientHistory(node: PatientHistory, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePatientHistory(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.startOfStudyDate) && includeChildren(node.startOfStudyDate)) {
            this.walk(node.startOfStudyDate, includeChildren);
        }
        node.patientVisits.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.patientNotAvailableDates.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPatientHistory(node);
            }
        }
    }

    private walkTimeExpression(node: TimeExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeTimeExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterTimeExpression(node);
            }
        }
    }

    private walkString(node: String, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeString(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterString(node);
            }
        }
    }

    private walkScheduleExpression(node: ScheduleExpression, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeScheduleExpression(node);
            }
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterScheduleExpression(node);
            }
        }
    }

    private walkAvailability(node: Availability, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeAvailability(node);
            }
        }
        // work on children in the model tree
        node.staffLevels.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterAvailability(node);
            }
        }
    }

    private walkPatientInfo(node: PatientInfo, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePatientInfo(node);
            }
        }
        // work on children in the model tree
        node.patientHistories.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPatientInfo(node);
            }
        }
    }

    private walkPatientHistoryUnit(node: PatientHistoryUnit, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforePatientHistoryUnit(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.patientHistory) && includeChildren(node.patientHistory)) {
            this.walk(node.patientHistory, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterPatientHistoryUnit(node);
            }
        }
    }

    private walkStudyConfiguration(node: StudyConfiguration, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStudyConfiguration(node);
            }
        }
        // work on children in the model tree
        node.periods.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.tasks.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.systemAccesses.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.staffing.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        node.roles.forEach((p) => {
            if (notNullOrUndefined(includeChildren) && includeChildren(p)) {
                this.walk(p, includeChildren);
            }
        });
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.description) && includeChildren(node.description)) {
            this.walk(node.description, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStudyConfiguration(node);
            }
        }
    }

    private walkStudyConfigurationModel(node: StudyConfigurationModel, includeChildren?: (elem: FreNode) => boolean) {
        let stopWalkingThisNode: boolean = false;
        for (const worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execBeforeStudyConfigurationModel(node);
            }
        }
        // work on children in the model tree
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.configuration) && includeChildren(node.configuration)) {
            this.walk(node.configuration, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.availability) && includeChildren(node.availability)) {
            this.walk(node.availability, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.patients) && includeChildren(node.patients)) {
            this.walk(node.patients, includeChildren);
        }
        if (notNullOrUndefined(includeChildren) && notNullOrUndefined(node.currentPatient) && includeChildren(node.currentPatient)) {
            this.walk(node.currentPatient, includeChildren);
        }

        for (let worker of this.myWorkers) {
            if (!stopWalkingThisNode) {
                stopWalkingThisNode = worker.execAfterStudyConfigurationModel(node);
            }
        }
    }
}
