// Generated by the Freon Language Generator.
// TEMPLATE BoxProviderTemplate.generateBoxProvider(...)

import { Box, BoxUtil, FreBoxProvider, FreProjectionHandler, BoxFactory, FreListInfo } from "@freon4dsl/core";
import { Availability } from "../language/index.js";

/**
 * This class implements the box provider for a single node of type Availability.
 * The box provider is able to create the (tree of) boxes for the node, based
 * on the projections that are currently selected by the user.
 * The top of the tree of boxes is always a box of type ElementBox, which is
 * a box that will never be rendered itself, only its content will. Thus, we
 * have a stable entry in the complete box tree for every FreNode node.
 */
export class AvailabilityBoxProvider extends FreBoxProvider {
    constructor(mainHandler: FreProjectionHandler) {
        super(mainHandler);
        this.knownBoxProjections = ["default", "parser"];
        this.knownTableProjections = ["default"];
        this.conceptName = "Availability";
    }

    protected getContent(projectionName: string): Box {
        // console.log("GET CONTENT " + this._node?.freId() + ' ' +  this._node?.freLanguageConcept() + ' ' + projectionName);
        // see if we need to use a custom projection
        if (!this.knownBoxProjections.includes(projectionName) && !this.knownTableProjections.includes(projectionName)) {
            const BOX: Box = this.mainHandler.executeCustomProjection(this._node, projectionName);
            if (!!BOX) {
                // found one, so return it
                return BOX;
            }
        } else {
            // select the box to return based on the projectionName
            if (projectionName === "default") {
                return this.getDefault();
            } else if (projectionName === "parser") {
                return this.getParser();
            }
        }
        // in all other cases, return the default
        return this.getDefault();
    }

    private getDefault(): Box {
        return BoxFactory.verticalLayout(
            this._node as Availability,
            "Availability-overall",
            "",
            [
                BoxUtil.labelBox(this._node as Availability, "STAFFING", "top-1-line-0-item-0"),
                BoxUtil.indentBox(
                    this._node as Availability,
                    2,
                    "1",
                    BoxFactory.horizontalLayout(
                        this._node as Availability,
                        "Availability-hlist-line-1",
                        "",
                        [
                            BoxUtil.labelBox(this._node as Availability, "Number of CRCs Normally Available:", "top-1-line-1-item-0"),
                            BoxUtil.textBox(this._node as Availability, "baselineStaff"),
                        ],
                        { selectable: false },
                    ),
                ),
                BoxUtil.emptyLineBox(this._node as Availability, "Availability-empty-line-2"),
                BoxUtil.indentBox(
                    this._node as Availability,
                    2,
                    "3",
                    BoxUtil.labelBox(this._node as Availability, "Staffing Level Changes:", "top-1-line-3-item-0"),
                ),
                BoxUtil.indentBox(
                    this._node as Availability,
                    2,
                    "4",
                    BoxUtil.verticalPartListBox(
                        this._node as Availability,
                        (this._node as Availability).staffLevels,
                        "staffLevels",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
                BoxUtil.emptyLineBox(this._node as Availability, "Availability-empty-line-5"),
            ],
            { cssClass: "Availability" },
        );
    }

    private getParser(): Box {
        return BoxFactory.verticalLayout(
            this._node as Availability,
            "Availability-overall",
            "",
            [
                BoxUtil.labelBox(this._node as Availability, "STAFFING", "top-1-line-0-item-0"),
                BoxUtil.indentBox(
                    this._node as Availability,
                    2,
                    "1",
                    BoxFactory.horizontalLayout(
                        this._node as Availability,
                        "Availability-hlist-line-1",
                        "",
                        [
                            BoxUtil.labelBox(this._node as Availability, "Number of CRCs Normally Available:", "top-1-line-1-item-0"),
                            BoxUtil.textBox(this._node as Availability, "baselineStaff"),
                        ],
                        { selectable: false },
                    ),
                ),
                BoxUtil.indentBox(
                    this._node as Availability,
                    2,
                    "2",
                    BoxUtil.labelBox(this._node as Availability, "Staffing Level Changes:", "top-1-line-2-item-0"),
                ),
                BoxUtil.indentBox(
                    this._node as Availability,
                    4,
                    "3",
                    BoxUtil.verticalPartListBox(
                        this._node as Availability,
                        (this._node as Availability).staffLevels,
                        "staffLevels",
                        FreListInfo.NullListInfo,
                        this.mainHandler,
                    ),
                ),
                BoxUtil.emptyLineBox(this._node as Availability, "Availability-empty-line-4"),
            ],
            { cssClass: "Availability" },
        );
    }
}
