// Generated by the Freon Language Generator.
import {
    FreNode,
    FreProjection,
    FreProjectionHandler,
    FreTableDefinition,
    ownerOfType,
    Box,
    createDefaultExpressionBox,
    TableRowBox,
    BoxFactory,
    BoxUtil,
    FreNodeReference,
    LimitedDisplay,
    NumberDisplay,
    TextBox,
} from "@freon4dsl/core"
import {
    StudyConfiguration,
    Description,
    Period,
    Event,
    Task,
    TaskReference,
    AbstractTask,
    Step,
    SystemAccess,
    Reference,
    Person,
    TypeOfEvent,
    PatientInfo,
    PatientHistory,
    NumberLiteralExpression,
    SharedTask,
} from "../language/gen/index.js"
import { StudyConfigurationModelEnvironment } from "../config/gen/StudyConfigurationModelEnvironment.js"

/**
 * Class CustomStudyConfigurationModelProjection provides an entry point for the language engineer to
 * define custom build additions to the editor.
 * These are merged with the custom build additions and other definition-based editor parts
 * in a three-way manner. For each modelelement,
 * (1) if a custom build creator/behavior is present, this is used,
 * (2) if a creator/behavior based on one of the editor definition is present, this is used,
 * (3) if neither (1) nor (2) yields a result, the default is used.
 */

export class CustomStudyConfigurationModelProjection implements FreProjection {
    name: string = "Custom"
    handler: FreProjectionHandler
    nodeTypeToBoxMethod: Map<string, (node: FreNode) => Box> = new Map<string, (node: FreNode) => Box>([
        ["StudyConfiguration", this.projectStudyConfiguration],
        ["Description", this.projectDescription],
        ["Period", this.projectPeriod],
        ["Event", this.projectEvent],
        ["Task", this.projectTaskOLD],
        ["TaskReference", this.projectTaskOLD],
        // ["Task", this.projectTask],
        // ["TaskReference", this.projectTaskReference],
        // ["SharedTask", this.projectSharedTask],
        ["Step", this.projectStep],
        ["Reference", this.projectReference],
        // ["SystemAccess", this.projectSystem],
        ["Person", this.projectPerson],
        ["PatientInfo", this.projectPatientInfo],
        ["PatientHistory", this.projectPatientHistory],
        ["NumberLiteralExpression", this.createNumberLiteralBox],
    ])

    nodeTypeToTableDefinition: Map<string, () => FreTableDefinition> = new Map<string, () => FreTableDefinition>([
        // register your custom table definition methods here
        // ['NAME_OF_CONCEPT', this.TABLE_DEFINITION_FOR_CONCEPT],
    ])

    getTableHeadersFor(projectionName: string): TableRowBox {
        return null
    }

    // For each table projection to override the meta-programming pattern is:
    // - Use a type assertion to access the private getTableRowFor_default method on the XXXProvider prototype
    // - Assign the new implementation to the method
    //
    // overrideTableProjects() {
    //     const taskBoxProviderPrototype = TaskBoxProvider.prototype as any;
    //     taskBoxProviderPrototype.getTableRowFor_default = newGetTableRowFor_defaultTaskImplementation;

    //     const systemAccessBoxProviderPrototype = SystemAccessBoxProvider.prototype as any;
    //     systemAccessBoxProviderPrototype.getTableRowFor_default = newGetTableRowFor_defaultSystemAccessImplementation;
    // }

    ////////////////////////////////////////////////////////////////////
    createNumberLiteralBox(num: NumberLiteralExpression): Box {
        const numBox: Box = BoxUtil.numberBox(num, "value", NumberDisplay.SELECT)
        if (numBox instanceof TextBox) {
            numBox.deleteWhenEmpty = true
        }
        return createDefaultExpressionBox(num, [numBox], { selectable: false })
    }

    /**
     * Creates a study configuration box based on the provided element.
     *
     * @param element - The study configuration element.
     * @returns The created study configuration box.
     */
    projectStudyConfiguration(studyconfig: StudyConfiguration): Box {
        const element: StudyConfiguration = studyconfig
        let box: Box = BoxFactory.verticalLayout(element, "StudyConfiguration-overall", "", [
            BoxUtil.partWrapperBox(
                element,
                "periods",
                "ListGroupComponent",
                BoxUtil.verticalPartListBox(element, element.periods, "periods", null, this.handler),
                {
                    params: [
                        { key: "cssClass", value: "type1" },
                        { key: "canAdd", value: "true" },
                        { key: "canExpand", value: "true" },
                        { key: "isExpanded", value: "true" },
                        { key: "selectable", value: "false" },
                        { key: "label", value: "Study Periods" },
                    ],
                },
            ),
            ...(element.showSharedTasks === true
                ? [
                      BoxUtil.partWrapperBox(
                          element,
                          "shared-tasks",
                          "ListGroupComponent",
                          BoxUtil.verticalPartListBox(element, element.tasks, "tasks", null, this.handler),
                          {
                              params: [
                                  { key: "cssClass", value: "type1" },
                                  { key: "canAdd", value: "true" },
                                  { key: "canExpand", value: "true" },
                                  { key: "isExpanded", value: "false" },
                                  { key: "selectable", value: "false" },
                                  { key: "label", value: "Shared Tasks" },
                              ],
                          },
                      ),
                  ]
                : []),
            ...(element.showSystems === true
                ? [
                      BoxUtil.partWrapperBox(
                          element,
                          "shared-systems",
                          "ListGroupComponent",
                          BoxUtil.verticalPartListBox(element, element.systemAccesses, "systemAccesses", null, this.handler),
                          {
                              params: [
                                  { key: "cssClass", value: "type1" },
                                  { key: "canAdd", value: "true" },
                                  { key: "canExpand", value: "true" },
                                  { key: "isExpanded", value: "false" },
                                  { key: "selectable", value: "false" },
                                  { key: "label", value: "Systems" },
                              ],
                          },
                      ),
                  ]
                : []),
            ...(element.showPeople === true
                ? [
                      BoxUtil.partWrapperBox(
                          element,
                          "shared-people",
                          "ListGroupComponent",
                          BoxUtil.getBoxOrAction(element, "staffing", "Staffing", this.handler),
                          {
                              params: [
                                  { key: "cssClass", value: "type1" },
                                  { key: "canAdd", value: "true" },
                                  { key: "canExpand", value: "true" },
                                  { key: "isExpanded", value: "false" },
                                  { key: "selectable", value: "false" },
                                  { key: "label", value: "People" },
                              ],
                          },
                      ),
                  ]
                : []),
        ])
        return box
    }

    projectDescription(description: Description): Box {
        const element: Description = description
        const ph = "<description>"
        let box: Box = 
            BoxUtil.partWrapperBox(
                element,
                "study-part-description",
                "MultilineTextComponent", 
                BoxUtil.textBox(element, "text"),
                {
                    params: [
                        { key: "selectable", value: "false" },
                        { key: "placeholder", value: ph }
                    ],
                },
            )
        return box;  
    }        

    //     return new MultiLineTextBox2(
    //         element,
    //         "study-part-description",
    //         () => {
    //             return element.text
    //         },
    //         (t: string) => {
    //             element.text = t
    //         },
    //         { placeHolder: ph, cssClass: "desc" },
    //     )
    // }

    projectPeriod(period: Period): Box {
        const element: Period = period
        const showDescriptions = ((element.freOwner() as Period).freOwner() as StudyConfiguration).showDescriptions
        let box: Box = 
            BoxUtil.partWrapperBox(
                element,
                "period",
                "ItemGroupComponent", 
                BoxFactory.verticalLayout(
                    element,
                    "period-detail",
                    "",
                    [
                        ...(showDescriptions
                            ? [
                                BoxFactory.horizontalLayout(
                                    element,
                                    "period-hlist-line-1",
                                    "",
                                    [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)],
                                    { selectable: false, cssClass: "align-top" },
                                ),
                            ] : []
                        ),
                        BoxUtil.partWrapperBox(
                            element,
                            "events",
                            "ListGroupComponent",
                            BoxUtil.verticalPartListBox(
                                element, 
                                element.events, 
                                "events", 
                                null, 
                                this.handler
                            ),
                            { 
                                params: [
                                    { key: "cssClass", value: "type2" },
                                    { key: "canAdd", value: "true" },
                                    { key: "canExpand", value: "true" },
                                    { key: "isExpanded", value: "false" },
                                    { key: "selectable", value: "false" },
                                    { key: "label", value: "Events" },
                                ],
                            },
                        ),
                    ]
                ),
                {
                    params: [
                        { key: "cssClass", value: "type1" },
                        { key: "canDelete", value: "true" },
                        { key: "canDuplicate", value: "true" },
                        { key: "canExpand", value: "true" },
                        { key: "isExpanded", value: "false" },
                        { key: "selectable", value: "false" },
                        { key: "label", value: "Period" },
                    ],
                },
            )
        return box;
    }

    projectEvent(event: Event): Box {
        const element: Event = event
        const showScheduling = ((element.freOwner() as Period).freOwner() as StudyConfiguration).showScheduling
        const showChecklists = ((element.freOwner() as Period).freOwner() as StudyConfiguration).showChecklists
        const showDescriptions = ((element.freOwner() as Period).freOwner() as StudyConfiguration).showDescriptions
        let box: Box = BoxUtil.partWrapperBox(
            element,
            "event",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "Event-detail", "", [
                BoxFactory.horizontalLayout(
                    element as Event,
                    "Event-hlist-line-1",
                    "",
                    [
                        BoxUtil.labelBox(element as Event, "This is a", "top-1-line-1-item-0", { selectable: false }),
                        BoxUtil.limitedBox(
                            element as Event,
                            "typeOfEvent",
                            (selected: string) => {
                                ;(element as Event).typeOfEvent = FreNodeReference.create<TypeOfEvent>(selected, "TypeOfEvent")
                            },
                            LimitedDisplay.SELECT,
                            StudyConfigurationModelEnvironment.getInstance().scoper,
                        ),
                        BoxUtil.labelBox(element as Event, "that is also referred to as", "top-1-line-1-item-2"),
                        BoxUtil.textBox(element as Event, "alternativeName"),
                    ],
                    { selectable: true },
                ),

                ...(showDescriptions === true ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),

                ...(showScheduling === true
                    ? [
                          BoxUtil.partWrapperBox(
                              element,
                              "schedule",
                              "ListGroupComponent",
                              BoxUtil.getBoxOrAction(element, "schedule", "EventSchedule", this.handler),
                              {
                                  params: [
                                      { key: "cssClass", value: "type3" },
                                      { key: "canExpand", value: "true" },
                                      { key: "isExpanded", value: "false" },
                                      { key: "selectable", value: "false" },
                                      { key: "label", value: "Schedule" },
                                  ],
                              },
                          ),
                      ]
                    : []),

                ...(showChecklists === true
                    ? [
                          BoxUtil.partListWrapperBox(
                              element,
                              "tasks",
                              "ListGroupComponent",
                              BoxUtil.verticalPartListBox(element, element.tasks, "tasks", null, this.handler),
                              {
                                  params: [
                                      { key: "cssClass", value: "type3" },
                                      { key: "canAdd", value: "true" },
                                      { key: "canExpand", value: "true" },
                                      { key: "isExpanded", value: "false" },
                                      { key: "selectable", value: "false" },
                                      { key: "label", value: "Checklist" },
                                  ],
                              },
                          ),
                      ]
                    : []),
            ]),
            {
                params: [
                    { key: "cssClass", value: "type2" },
                    { key: "canDelete", value: "true" },
                    { key: "canDuplicate", value: "true" },
                    { key: "canExpand", value: "true" },
                    { key: "isExpanded", value: "false" },
                    { key: "selectable", value: "false" },
                    { key: "label", value: "Event" },
                ],
            },
        )
        return box
    }

    projectTaskOLD(abstract: AbstractTask) {
        let box: Box
        let isShareable: boolean = true
        const event: Event = ownerOfType(abstract, "Event") as Event
        const studyConfiguration: StudyConfiguration = ownerOfType(abstract, "StudyConfiguration") as StudyConfiguration
        const showDescriptions = studyConfiguration ? studyConfiguration.showDescriptions : false
        if (event) {
            // event task
            if (abstract instanceof Task) {
                // in-line task
                let element: Task = abstract as Task
                box = BoxUtil.partWrapperBox(
                    element,
                    "task",
                    "ItemGroupComponent",
                    BoxFactory.verticalLayout(element, "task-overall", "", [
                        ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
                        BoxUtil.partWrapperBox(
                            element,
                            "steps",
                            "ListGroupComponent",
                            BoxUtil.verticalPartListBox(element, element.steps, "steps", null, this.handler),
                            {
                                params: [
                                    { key: "cssClass", value: "type4" },
                                    { key: "canAdd", value: "true" },
                                    { key: "canExpand", value: "true" },
                                    { key: "isExpanded", value: "false" },
                                    { key: "selectable", value: "false" },
                                    { key: "label", value: "Steps" },
                                ],
                            },
                        ),
                    ]),
                    {
                        params: [
                            { key: "cssClass", value: "type3" },
                            { key: "canDelete", value: "true" },
                            { key: "canDuplicate", value: "true" },
                            { key: "canExpand", value: "true" },
                            { key: "isExpanded", value: "false" },
                            { key: "selectable", value: "false" },
                            { key: "label", value: "Task" },
                        ],
                    },
                )
            } else {
                // task Reference
                let taskRef: TaskReference = abstract as TaskReference
                let element: Task = taskRef.$task
                if (element) {
                    //with selection
                    box = BoxUtil.partWrapperBox(
                        element,
                        "task",
                        "ItemGroupComponent",
                        BoxFactory.verticalLayout(element, "task-overall", "", [
                            ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
                            BoxUtil.partWrapperBox(
                                element,
                                "steps",
                                "ListGroupComponent",
                                BoxUtil.verticalPartListBox(element, element.steps, "steps", null, this.handler),
                                {
                                    params: [
                                        { key: "cssClass", value: "type4" },
                                        { key: "canAdd", value: "true" },
                                        { key: "canExpand", value: "true" },
                                        { key: "isExpanded", value: "false" },
                                        { key: "selectable", value: "false" },
                                        { key: "label", value: "Steps" },
                                    ],
                                },
                            ),
                        ]),
                        {
                            params: [
                                { key: "cssClass", value: "type3" },
                                { key: "canDelete", value: "true" },
                                { key: "canDuplicate", value: "true" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "false" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Task" },
                            ],
                        },
                    )
                } else {
                    box = BoxUtil.partWrapperBox(element, "task", "ItemGroupComponent", BoxFactory.label(taskRef, "task-reference", "No task details"), {
                        params: [
                            { key: "cssClass", value: "type3" },
                            { key: "canExpand", value: "false" },
                            { key: "canDelete", value: "true" },
                            { key: "isRequired", value: "true" },
                        ],
                    })
                }
            }
        } else {
            //shared task
            let element: Task = abstract as Task
            let isShared = true
            box = BoxUtil.partWrapperBox(
                element,
                "task",
                "ItemGroupComponent",
                BoxFactory.verticalLayout(element, "task-overall", "", [
                    ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
                    BoxUtil.partWrapperBox(
                        element,
                        "steps",
                        "ListGroupComponent",
                        BoxUtil.verticalPartListBox(element, element.steps, "steps", null, this.handler),
                        {
                            params: [
                                { key: "cssClass", value: "type4" },
                                { key: "canAdd", value: "true" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "false" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Steps" },
                            ],
                        },
                    ),
                ]),
                {
                    params: [
                        { key: "cssClass", value: "type3" },
                        { key: "canShare", value: "false" },
                        { key: "canDelete", value: "false" },
                        { key: "isRequired", value: "true" },
                    ],
                },
            )
        }
        return box
    }

    projectTask(task: Task) {
        let box: Box
        const studyConfiguration: StudyConfiguration = ownerOfType(task, "StudyConfiguration") as StudyConfiguration
        const showDescriptions = studyConfiguration ? studyConfiguration.showDescriptions : false
        let element: Task = task as Task
        box = BoxUtil.partWrapperBox(
            element,
            "task",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "task-overall", "", [
                ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
                BoxUtil.partWrapperBox(
                    element,
                    "steps",
                    "ListGroupComponent",
                    BoxUtil.verticalPartListBox(element, element.steps, "steps", null, this.handler),
                    {
                        params: [
                            { key: "cssClass", value: "type4" },
                            { key: "canAdd", value: "true" },
                            { key: "canExpand", value: "true" },
                            { key: "isExpanded", value: "false" },
                            { key: "selectable", value: "false" },
                            { key: "label", value: "Steps" },
                        ],
                    },
                ),
            ]),
            {
                params: [
                    { key: "cssClass", value: "type3" },
                    { key: "canDelete", value: "true" },
                    { key: "canDuplicate", value: "true" },
                    { key: "canExpand", value: "true" },
                    { key: "isExpanded", value: "false" },
                    { key: "selectable", value: "false" },
                    { key: "label", value: "Task" },
                ],
            },
        )
        return box
    }

    projectTaskReference(taskReference: TaskReference) {
        let box: Box
        const studyConfiguration: StudyConfiguration = ownerOfType(taskReference, "StudyConfiguration") as StudyConfiguration
        const showDescriptions = studyConfiguration ? studyConfiguration.showDescriptions : false
        let element: TaskReference = taskReference
        let sharedTask: SharedTask = element.$task as SharedTask
        if (sharedTask) {
            //with selection
            box = BoxUtil.partWrapperBox(
                element,
                "task",
                "ItemGroupComponent",
                BoxFactory.verticalLayout(element, "task-overall", "", [
                    ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
                    BoxUtil.partWrapperBox(
                        element,
                        "steps",
                        "ListGroupComponent",
                        BoxUtil.verticalPartListBox(element, element.steps, "steps", null, this.handler),
                        {
                            params: [
                                { key: "cssClass", value: "type4" },
                                { key: "canAdd", value: "true" },
                                { key: "canExpand", value: "true" },
                                { key: "isExpanded", value: "false" },
                                { key: "selectable", value: "false" },
                                { key: "label", value: "Steps" },
                            ],
                        },
                    ),
                ]),
                {
                    params: [
                        { key: "cssClass", value: "type3" },
                        { key: "canDelete", value: "true" },
                        { key: "canDuplicate", value: "true" },
                        { key: "canExpand", value: "true" },
                        { key: "isExpanded", value: "false" },
                        { key: "selectable", value: "false" },
                        { key: "label", value: "Task" },
                    ],
                },
            )
        } else {
            // without selection
            const tmpTask: SharedTask = SharedTask.create({ name: "" }) as SharedTask
            let refToTask = FreNodeReference.create("", "SharedTask") as FreNodeReference<SharedTask>
            refToTask.referred = tmpTask
            element.task = refToTask
            box = BoxUtil.partWrapperBox(element, "task", "ItemGroupComponent", BoxFactory.label(element, "task-reference", "No task details"), {
                params: [
                    { key: "cssClass", value: "type3" },
                    { key: "canExpand", value: "false" },
                    { key: "canDelete", value: "true" },
                    { key: "isRequired", value: "true" },
                ],
            })
        }
        return box
    }

    projectSharedTask(sharedTask: SharedTask) {
        let box: Box
        const studyConfiguration: StudyConfiguration = ownerOfType(sharedTask, "StudyConfiguration") as StudyConfiguration
        const showDescriptions = studyConfiguration ? studyConfiguration.showDescriptions : false
        //shared task
        let element: Task = sharedTask as Task
        let isShared = true
        box = BoxUtil.partWrapperBox(
            element,
            "task",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "task-overall", "", [
                ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
                BoxUtil.partWrapperBox(
                    element,
                    "steps",
                    "ListGroupComponent",
                    BoxUtil.verticalPartListBox(element, element.steps, "steps", null, this.handler),
                    {
                        params: [
                            { key: "cssClass", value: "type4" },
                            { key: "canAdd", value: "true" },
                            { key: "canExpand", value: "true" },
                            { key: "isExpanded", value: "false" },
                            { key: "selectable", value: "false" },
                            { key: "label", value: "Steps" },
                        ],
                    },
                ),
            ]),
            {
                params: [
                    { key: "cssClass", value: "type3" },
                    { key: "canShare", value: "false" },
                    { key: "canDelete", value: "false" },
                    { key: "isRequired", value: "true" },
                ],
            },
        )
        return box
    }

    projectStep(element: Step) {
        const studyConfiguration: StudyConfiguration = ownerOfType(element, "StudyConfiguration") as StudyConfiguration
        const showDescriptions = studyConfiguration ? studyConfiguration.showDescriptions : false
        const showReferences = studyConfiguration ? studyConfiguration.showReferences : false
        const showSystems = studyConfiguration ? studyConfiguration.showSystems : false
        const showPeople = studyConfiguration ? studyConfiguration.showPeople : false
        let box: Box = BoxUtil.partWrapperBox(
            element,
            "step",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "step-overall", "", [
                ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "detailsDescription", "Description", this.handler)] : []),
                ...(showReferences
                    ? [
                          BoxUtil.partWrapperBox(
                              element,
                              "references",
                              "ListGroupComponent",
                              BoxUtil.verticalPartListBox(element, element.references, "references", null, this.handler),
                              {
                                  params: [
                                      { key: "cssClass", value: "type5" },
                                      { key: "canAdd", value: "true" },
                                      { key: "canExpand", value: "true" },
                                      { key: "isExpanded", value: "false" },
                                      { key: "selectable", value: "false" },
                                      { key: "label", value: "References" },
                                  ],
                              },
                          ),
                      ]
                    : []),
                ...(showSystems
                    ? [
                          BoxUtil.partWrapperBox(
                              element,
                              "systems",
                              "ListGroupComponent",
                              BoxUtil.verticalPartListBox(element, element.systems, "systems", null, this.handler),
                              {
                                  params: [
                                      { key: "cssClass", value: "type5" },
                                      { key: "canAdd", value: "true" },
                                      { key: "canExpand", value: "true" },
                                      { key: "isExpanded", value: "false" },
                                      { key: "selectable", value: "false" },
                                      { key: "label", value: "Systems" },
                                  ],
                              },
                          ),
                      ]
                    : []),
                ...(showPeople
                    ? [
                          BoxUtil.partWrapperBox(
                              element,
                              "people",
                              "ListGroupComponent",
                              BoxUtil.verticalPartListBox(element, element.people, "people", null, this.handler),
                              {
                                  params: [
                                      { key: "cssClass", value: "type5" },
                                      { key: "canAdd", value: "true" },
                                      { key: "canExpand", value: "true" },
                                      { key: "isExpanded", value: "false" },
                                      { key: "selectable", value: "false" },
                                      { key: "label", value: "People" },
                                  ],
                              },
                          ),
                      ]
                    : []),
            ]),
            {
                params: [
                    { key: "cssClass", value: "type4" },
                    { key: "canExpand", value: "true" },
                    { key: "isExpanded", value: "false" },
                    { key: "selectable", value: "false" },
                    { key: "label", value: "Step" },
                ],
            },
        )
        return box
    }

    projectReference(element: Reference) {
        let box: Box = BoxUtil.partWrapperBox(
            element,
            "reference",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "reference-overall", "", [BoxUtil.textBox(element, "link")]),
            {
                params: [
                    { key: "cssClass", value: "type5" },
                    { key: "canShare", value: "true" },
                    { key: "isRequired", value: "true" },
                ],
            },
        )
        return box
    }

    projectSystem(element: SystemAccess) {
        const studyConfiguration: StudyConfiguration = ownerOfType(element, "StudyConfiguration") as StudyConfiguration
        const showDescriptions = studyConfiguration ? studyConfiguration.showDescriptions : false
        let box: Box = BoxUtil.partWrapperBox(
            element,
            "system",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "system-overall", "", [
                BoxUtil.textBox(element, "functionName"),
                ...(showDescriptions ? [BoxUtil.getBoxOrAction(element, "description", "Description", this.handler)] : []),
            ]),
            {
                params: [
                    { key: "cssClass", value: "type5" },
                    { key: "canShare", value: "true" },
                    { key: "isRequired", value: "true" },
                ],
            },
        )
        return box
    }

    projectPerson(element: Person) {
        let box: Box = BoxUtil.partWrapperBox(
            element,
            "person",
            "ItemGroupComponent",
            BoxFactory.verticalLayout(element, "person-overall", "", [
                BoxUtil.textBox(element, "email"),
                BoxUtil.textBox(element, "phoneNumber"),
                BoxUtil.getBoxOrAction(element, "role", "StaffRole", this.handler),
            ]),
            {
                params: [
                    { key: "cssClass", value: "type5" },
                    { key: "canShare", value: "true" },
                    { key: "isRequired", value: "true" },
                ],
            },
        )
        return box
    }

    projectPatientInfo(patientInfo: PatientInfo) {
        const element: PatientInfo = patientInfo
        let box = BoxUtil.partWrapperBox(
            element,
            "patients",
            "ListGroupComponent",
            BoxUtil.verticalPartListBox(element, element.patientHistories, "patientHistories", null, this.handler),
            {
                params: [
                    { key: "cssClass", value: "type1" },
                    { key: "isExpanded", value: "true" },
                    { key: "canAdd", value: "true" },
                    { key: "selectable", value: "false" },
                ],
            },
        )
        return box
    }

    projectPatientHistory(patientHistory: PatientHistory) {
        const element: PatientHistory = patientHistory
        let box: Box = BoxFactory.verticalLayout(
            // Removed the item group box because the history is now only displayed under a single patient and entire histories are added by adding a patient in the
            element,
            "PatientHistory-overall",
            "",
            [
                BoxUtil.partWrapperBox(
                    element,
                    "patientvisits",
                    "ListGroupComponent",
                    //TODO: add and deleted button needed; allow drag-and-drop reordering
                    //TODO: decide if it's worth auto-populating all the visits without a complete date
                    BoxUtil.verticalPartListBox(element, element.patientVisits, "patientVisits", null, this.handler),
                    {
                        params: [
                            { key: "cssClass", value: "type1" },
                            { key: "isExpanded", value: "true" },
                            { key: "canAdd", value: "true" },
                            { key: "selectable", value: "false" },
                        ],
                    },
                ),
                BoxUtil.partWrapperBox(
                    element,
                    "patientNotAvailableDates",
                    "ListGroupComponent",
                    BoxUtil.verticalPartListBox(element, element.patientNotAvailableDates, "patientNotAvailableDates", null, this.handler),
                    {
                        params: [
                            { key: "cssClass", value: "type1" },
                            { key: "isExpanded", value: "true" },
                            { key: "canAdd", value: "true" },
                            { key: "selectable", value: "false" },
                        ],
                    },
                ),
            ],
        )
        return box
    }
}
