// Generated by the Freon Language Generator.
import { Box, BoxFactory, BoxUtil, createDefaultExpressionBox, FreNode, FreProjection, FreProjectionHandler, FreTableDefinition, NumberDisplay, TableRowBox, TextBox } from "@freon4dsl/core"
import { Description, NumberLiteralExpression, PatientHistory, PatientInfo } from "../language/gen/index.js"

/**
 * Class CustomStudyConfigurationModelProjection provides an entry point for the language engineer to
 * define custom build additions to the editor.
 * These are merged with the custom build additions and other definition-based editor parts
 * in a three-way manner. For each modelelement,
 * (1) if a custom build creator/behavior is present, this is used,
 * (2) if a creator/behavior based on one of the editor definition is present, this is used,
 * (3) if neither (1) nor (2) yields a result, the default is used.
 */

export class CustomStudyConfigurationModelProjection implements FreProjection {
    name: string = "Custom"
    handler: FreProjectionHandler
    nodeTypeToBoxMethod: Map<string, (node: FreNode) => Box> = new Map<string, (node: FreNode) => Box>([
        // ["StudyConfiguration", this.projectStudyConfiguration],
        // ["Description", this.projectDescription],
        // ["Period", this.projectPeriod],
        // ["Event", this.projectEvent],
        // ["Task", this.projectTaskOLD],
        // ["TaskReference", this.projectTaskOLD],
        // ["Task", this.projectTask],
        // ["TaskReference", this.projectTaskReference],
        // ["SharedTask", this.projectSharedTask],
        // ["Step", this.projectStep],
        // ["Reference", this.projectReference],
        // ["SystemAccess", this.projectSystem],
        ["PatientInfo", this.projectPatientInfo],
        ["PatientHistory", this.projectPatientHistory],
        ["NumberLiteralExpression", this.createNumberLiteralBox],
    ])

    nodeTypeToTableDefinition: Map<string, () => FreTableDefinition> = new Map<string, () => FreTableDefinition>([
        // register your custom table definition methods here
        // ['NAME_OF_CONCEPT', this.TABLE_DEFINITION_FOR_CONCEPT],
    ])

    getTableHeadersFor(projectionName: string): TableRowBox {
        return null
    }

    // For each table projection to override the meta-programming pattern is:
    // - Use a type assertion to access the private getTableRowFor_default method on the XXXProvider prototype
    // - Assign the new implementation to the method
    //
    // overrideTableProjects() {
    //     const taskBoxProviderPrototype = TaskBoxProvider.prototype as any;
    //     taskBoxProviderPrototype.getTableRowFor_default = newGetTableRowFor_defaultTaskImplementation;

    //     const systemAccessBoxProviderPrototype = SystemAccessBoxProvider.prototype as any;
    //     systemAccessBoxProviderPrototype.getTableRowFor_default = newGetTableRowFor_defaultSystemAccessImplementation;
    // }

    ////////////////////////////////////////////////////////////////////
    createNumberLiteralBox(num: NumberLiteralExpression): Box {
        const numBox: Box = BoxUtil.numberBox(num, "value", NumberDisplay.SELECT)
        if (numBox instanceof TextBox) {
            numBox.deleteWhenEmpty = true
        }
        return createDefaultExpressionBox(num, [numBox], { selectable: false })
    }

    projectDescription(description: Description): Box {
        const element: Description = description
        const ph = "<description>"
        let box: Box = 
            BoxUtil.partWrapperBox(
                element,
                "study-part-description",
                "MultilineTextComponent", 
                BoxUtil.textBox(element, "text"),
                {
                    params: [
                        { key: "selectable", value: "false" },
                        { key: "placeholder", value: ph }
                    ],
                },
            )
        return box;  
    }        

    projectPatientInfo(patientInfo: PatientInfo) {
        const element: PatientInfo = patientInfo
        let box = BoxUtil.partWrapperBox(
            element,
            "patients",
            "ListGroupComponent",
            BoxUtil.verticalPartListBox(element, element.patientHistories, "patientHistories", null, this.handler),
            {
                params: [
                    { key: "cssClass", value: "type1" },
                    { key: "isExpanded", value: "true" },
                    { key: "canAdd", value: "true" },
                    { key: "selectable", value: "false" },
                ],
            },
        )
        return box
    }

    projectPatientHistory(patientHistory: PatientHistory) {
        const element: PatientHistory = patientHistory
        let box: Box = BoxFactory.verticalLayout(
            // Removed the item group box because the history is now only displayed under a single patient and entire histories are added by adding a patient in the
            element,
            "PatientHistory-overall",
            "",
            [
                BoxUtil.partWrapperBox(
                    element,
                    "patientvisits",
                    "ListGroupComponent",
                    //TODO: add and deleted button needed; allow drag-and-drop reordering
                    //TODO: decide if it's worth auto-populating all the visits without a complete date
                    BoxUtil.verticalPartListBox(element, element.patientVisits, "patientVisits", null, this.handler),
                    {
                        params: [
                            { key: "cssClass", value: "type1" },
                            { key: "isExpanded", value: "true" },
                            { key: "canAdd", value: "true" },
                            { key: "selectable", value: "false" },
                        ],
                    },
                ),
                BoxUtil.partWrapperBox(
                    element,
                    "patientNotAvailableDates",
                    "ListGroupComponent",
                    BoxUtil.verticalPartListBox(element, element.patientNotAvailableDates, "patientNotAvailableDates", null, this.handler),
                    {
                        params: [
                            { key: "cssClass", value: "type1" },
                            { key: "isExpanded", value: "true" },
                            { key: "canAdd", value: "true" },
                            { key: "selectable", value: "false" },
                        ],
                    },
                ),
            ],
        )
        return box
    }
}
