// Generated by the Freon Language Generator.
import { FreProjection, FreCombinedActions, FreTyper, FreStdlib, FreScoper } from "@freon4dsl/core";
import { CustomExternalModelActions, CustomExternalModelProjection } from "../editor/index.js";
import { CustomExternalModelScoper } from "../scoper/index.js";
import { CustomExternalModelTyperPart } from "../typer/index.js";
import { CustomExternalModelValidator } from "../validator/index.js";
import { CustomExternalModelStdlib } from "../stdlib/index.js";
import { ExternalModelCheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomExternalModelProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomExternalModelActions()];
    // add your custom validations here
    customValidations: ExternalModelCheckerInterface[] = [new CustomExternalModelValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomExternalModelScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomExternalModelTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomExternalModelStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
