// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { RulesModelDefaultWorker } from "../utils/gen/RulesModelDefaultWorker.js";
import { RulesModelCheckerInterface } from "./gen/RulesModelValidator.js";

export class CustomRulesModelValidator extends RulesModelDefaultWorker implements RulesModelCheckerInterface {
    errorList: FreError[] = [];
}
