// Generated by the Freon Language Generator.
import { FreNode, FreNamedNode, FreScoper, FreScoperComposite, FreScoperBase, ownerOfType } from "@freon4dsl/core";
import { Study } from "../language/gen/index";
import { StudyExtractModelScoper } from "./gen/index";

/**
 * Class 'CustomStudyExtractModelScoper' is meant to be a convenient place to add any
 * custom code for scoping.
 */
export class CustomStudyExtractModelScoper extends StudyExtractModelScoper
{
    getVisibleElements(modelelement: FreNode, metatype?: string, excludeSurrounding?: boolean): FreNamedNode[] {
        const defaultScope: FreNamedNode[] = super.getVisibleElements(modelelement, metatype, excludeSurrounding)
        const parentStudy = ownerOfType(modelelement, "Study")
        const parent = defaultScope.findIndex(node => (node as Study) === parentStudy)
        if (parent !== -1) {
            defaultScope.splice(parent, 1)
        }
        return defaultScope
    }
}
