// Generated by the Freon Language Generator.
// TEMPLATE: InterfaceTemplate.generateInterface

import { type FreNode } from "@freon4dsl/core";

/**
 * Interface AccessedAt is the implementation of the interface with the same name in the language definition file.
 */
export interface AccessedAt extends FreNode {
    copy(): AccessedAt;
}
