// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import { MobxModelElementImpl, observableprim, type FreNode, FreParseLocation, notNullOrUndefined, FreUtils } from "@freon4dsl/core";
import { type EventTimeOfDay } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class BetweenTimes is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class BetweenTimes extends MobxModelElementImpl implements FreNode, EventTimeOfDay {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<BetweenTimes>): BetweenTimes {
        const result = new BetweenTimes(data.$id);
        if (notNullOrUndefined(data.startTimeAsString)) {
            result.startTimeAsString = data.startTimeAsString;
        }
        if (notNullOrUndefined(data.endTimeAsString)) {
            result.endTimeAsString = data.endTimeAsString;
        }
        if (notNullOrUndefined(data.startHour)) {
            result.startHour = data.startHour;
        }
        if (notNullOrUndefined(data.startMinute)) {
            result.startMinute = data.startMinute;
        }
        if (notNullOrUndefined(data.endHour)) {
            result.endHour = data.endHour;
        }
        if (notNullOrUndefined(data.endMinute)) {
            result.endMinute = data.endMinute;
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "BetweenTimes"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    startTimeAsString!: string; // implementation of startTimeAsString
    endTimeAsString!: string; // implementation of endTimeAsString
    startHour!: number; // implementation of startHour
    startMinute!: number; // implementation of startMinute
    endHour!: number; // implementation of endHour
    endMinute!: number; // implementation of endMinute

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, "startTimeAsString");
        this.startTimeAsString = "";
        observableprim(this, "endTimeAsString");
        this.endTimeAsString = "";
        observableprim(this, "startHour");
        this.startHour = 0;
        observableprim(this, "startMinute");
        this.startMinute = 0;
        observableprim(this, "endHour");
        this.endHour = 0;
        observableprim(this, "endMinute");
        this.endMinute = 0;

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): BetweenTimes {
        const result = new BetweenTimes();
        if (notNullOrUndefined(this.startTimeAsString)) {
            result.startTimeAsString = this.startTimeAsString;
        }
        if (notNullOrUndefined(this.endTimeAsString)) {
            result.endTimeAsString = this.endTimeAsString;
        }
        if (notNullOrUndefined(this.startHour)) {
            result.startHour = this.startHour;
        }
        if (notNullOrUndefined(this.startMinute)) {
            result.startMinute = this.startMinute;
        }
        if (notNullOrUndefined(this.endHour)) {
            result.endHour = this.endHour;
        }
        if (notNullOrUndefined(this.endMinute)) {
            result.endMinute = this.endMinute;
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<BetweenTimes>): boolean {
        let result: boolean = true;
        if (
            result &&
            toBeMatched.startTimeAsString !== null &&
            toBeMatched.startTimeAsString !== undefined &&
            toBeMatched.startTimeAsString.length > 0
        ) {
            result = result && this.startTimeAsString === toBeMatched.startTimeAsString;
        }
        if (
            result &&
            toBeMatched.endTimeAsString !== null &&
            toBeMatched.endTimeAsString !== undefined &&
            toBeMatched.endTimeAsString.length > 0
        ) {
            result = result && this.endTimeAsString === toBeMatched.endTimeAsString;
        }
        if (result && toBeMatched.startHour !== null && toBeMatched.startHour !== undefined) {
            result = result && this.startHour === toBeMatched.startHour;
        }
        if (result && toBeMatched.startMinute !== null && toBeMatched.startMinute !== undefined) {
            result = result && this.startMinute === toBeMatched.startMinute;
        }
        if (result && toBeMatched.endHour !== null && toBeMatched.endHour !== undefined) {
            result = result && this.endHour === toBeMatched.endHour;
        }
        if (result && toBeMatched.endMinute !== null && toBeMatched.endMinute !== undefined) {
            result = result && this.endMinute === toBeMatched.endMinute;
        }
        return result;
    }
}
