// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import { observablepart, type FreNode, FreParseLocation, notNullOrUndefined } from "@freon4dsl/core";
import { ComplianceWindow, Days } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate

/**
 * Class ComplianceWindowOf is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class ComplianceWindowOf extends ComplianceWindow implements FreNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<ComplianceWindowOf>): ComplianceWindowOf {
        const result = new ComplianceWindowOf(data.$id);
        if (notNullOrUndefined(data.maxDaysBefore)) {
            result.maxDaysBefore = data.maxDaysBefore;
        } else {
            result.maxDaysBefore = Days.create({});
        }
        if (notNullOrUndefined(data.maxDaysAfter)) {
            result.maxDaysAfter = data.maxDaysAfter;
        } else {
            result.maxDaysAfter = Days.create({});
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "ComplianceWindowOf"; // holds the metatype in the form of a string

    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed

    maxDaysBefore!: Days; // implementation of part 'maxDaysBefore'
    maxDaysAfter!: Days; // implementation of part 'maxDaysAfter'

    constructor(id?: string) {
        super(id);

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "maxDaysBefore");

        observablepart(this, "maxDaysAfter");
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): ComplianceWindowOf {
        const result = new ComplianceWindowOf();
        if (notNullOrUndefined(this.maxDaysBefore)) {
            result.maxDaysBefore = this.maxDaysBefore.copy();
        }
        if (notNullOrUndefined(this.maxDaysAfter)) {
            result.maxDaysAfter = this.maxDaysAfter.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<ComplianceWindowOf>): boolean {
        let result: boolean = super.match(toBeMatched);
        if (result && notNullOrUndefined(toBeMatched.maxDaysBefore)) {
            result = result && this.maxDaysBefore.match(toBeMatched.maxDaysBefore);
        }
        if (result && notNullOrUndefined(toBeMatched.maxDaysAfter)) {
            result = result && this.maxDaysAfter.match(toBeMatched.maxDaysAfter);
        }
        return result;
    }
}
