// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import { MobxModelElementImpl, observablepart, type FreNode, FreParseLocation, notNullOrUndefined, FreUtils } from "@freon4dsl/core";
import { type EventStart, EventWindow, type RepeatExpression, type EventTimeOfDay } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class EventSchedule is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class EventSchedule extends MobxModelElementImpl implements FreNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<EventSchedule>): EventSchedule {
        const result = new EventSchedule(data.$id);
        if (notNullOrUndefined(data.eventStart)) {
            result.eventStart = data.eventStart;
        }
        if (notNullOrUndefined(data.eventWindow)) {
            result.eventWindow = data.eventWindow;
        }
        if (notNullOrUndefined(data.eventRepeat)) {
            result.eventRepeat = data.eventRepeat;
        }
        if (notNullOrUndefined(data.eventTimeOfDay)) {
            result.eventTimeOfDay = data.eventTimeOfDay;
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "EventSchedule"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed

    eventStart!: EventStart; // implementation of part 'eventStart'
    eventWindow: EventWindow | undefined; // implementation of part 'eventWindow'
    eventRepeat: RepeatExpression | undefined; // implementation of part 'eventRepeat'
    eventTimeOfDay: EventTimeOfDay | undefined; // implementation of part 'eventTimeOfDay'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "eventStart");

        observablepart(this, "eventWindow");

        observablepart(this, "eventRepeat");

        observablepart(this, "eventTimeOfDay");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): EventSchedule {
        const result = new EventSchedule();
        if (notNullOrUndefined(this.eventStart)) {
            result.eventStart = this.eventStart.copy();
        }
        if (notNullOrUndefined(this.eventWindow)) {
            result.eventWindow = this.eventWindow.copy();
        }
        if (notNullOrUndefined(this.eventRepeat)) {
            result.eventRepeat = this.eventRepeat.copy();
        }
        if (notNullOrUndefined(this.eventTimeOfDay)) {
            result.eventTimeOfDay = this.eventTimeOfDay.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<EventSchedule>): boolean {
        let result: boolean = true;
        if (result && notNullOrUndefined(toBeMatched.eventStart)) {
            result = result && this.eventStart.match(toBeMatched.eventStart);
        }
        if (result && notNullOrUndefined(toBeMatched.eventWindow)) {
            if (this.eventWindow) {
                result = result && this.eventWindow.match(toBeMatched.eventWindow);
            }
        }
        if (result && notNullOrUndefined(toBeMatched.eventRepeat)) {
            if (this.eventRepeat) {
                result = result && this.eventRepeat.match(toBeMatched.eventRepeat);
            }
        }
        if (result && notNullOrUndefined(toBeMatched.eventTimeOfDay)) {
            if (this.eventTimeOfDay) {
                result = result && this.eventTimeOfDay.match(toBeMatched.eventTimeOfDay);
            }
        }
        return result;
    }
}
