// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import {
    MobxModelElementImpl,
    observableprim,
    observablepart,
    observablepartlist,
    type FreNamedNode,
    FreParseLocation,
    notNullOrUndefined,
    FreUtils,
    matchElementList,
} from "@freon4dsl/core";
import { Description, Reference, AbstractPerson, AbstractSystemAccess } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class Step is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class Step extends MobxModelElementImpl implements FreNamedNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<Step>): Step {
        const result = new Step(data.$id);
        if (notNullOrUndefined(data.name)) {
            result.name = data.name;
        }
        if (notNullOrUndefined(data.description)) {
            result.description = data.description;
        }
        if (notNullOrUndefined(data.references)) {
            data.references.forEach((x) => result.references.push(x));
        }
        if (notNullOrUndefined(data.people)) {
            data.people.forEach((x) => result.people.push(x));
        }
        if (notNullOrUndefined(data.systems)) {
            data.systems.forEach((x) => result.systems.push(x));
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "Step"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    name!: string; // implementation of name
    description: Description | undefined; // implementation of part 'description'
    references!: Reference[]; // implementation of part 'references'
    people!: AbstractPerson[]; // implementation of part 'people'
    systems!: AbstractSystemAccess[]; // implementation of part 'systems'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, "name");
        this.name = "";

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "description");

        observablepartlist(this, "references");
        observablepartlist(this, "people");
        observablepartlist(this, "systems");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): Step {
        const result = new Step();
        if (notNullOrUndefined(this.name)) {
            result.name = this.name;
        }
        if (notNullOrUndefined(this.description)) {
            result.description = this.description.copy();
        }
        if (notNullOrUndefined(this.references)) {
            this.references.forEach((x) => result.references.push(x.copy()));
        }
        if (notNullOrUndefined(this.people)) {
            this.people.forEach((x) => result.people.push(x.copy()));
        }
        if (notNullOrUndefined(this.systems)) {
            this.systems.forEach((x) => result.systems.push(x.copy()));
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<Step>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && notNullOrUndefined(toBeMatched.description)) {
            if (this.description) {
                result = result && this.description.match(toBeMatched.description);
            }
        }
        if (result && notNullOrUndefined(toBeMatched.references)) {
            result = result && matchElementList(this.references, toBeMatched.references);
        }
        if (result && notNullOrUndefined(toBeMatched.people)) {
            result = result && matchElementList(this.people, toBeMatched.people);
        }
        if (result && notNullOrUndefined(toBeMatched.systems)) {
            result = result && matchElementList(this.systems, toBeMatched.systems);
        }
        return result;
    }
}
