// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import {
    MobxModelElementImpl,
    observablepart,
    type FreNode,
    FreParseLocation,
    notNullOrUndefined,
    FreNodeReference,
    FreUtils,
} from "@freon4dsl/core";
import { TimeAmount, SimpleOperators } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class TimeAmountPart is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class TimeAmountPart extends MobxModelElementImpl implements FreNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<TimeAmountPart>): TimeAmountPart {
        const result = new TimeAmountPart(data.$id);
        if (notNullOrUndefined(data.timeAmount)) {
            result.timeAmount = data.timeAmount;
        } else {
            result.timeAmount = TimeAmount.create({});
        }
        if (notNullOrUndefined(data.operator)) {
            result.operator = data.operator;
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "TimeAmountPart"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed

    timeAmount!: TimeAmount; // implementation of part 'timeAmount'
    operator!: FreNodeReference<SimpleOperators>; // implementation of reference 'operator'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "timeAmount");

        observablepart(this, "operator");
        this.operator = FreNodeReference.create<SimpleOperators>(SimpleOperators.plus, "SimpleOperators");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): TimeAmountPart {
        const result = new TimeAmountPart();
        if (notNullOrUndefined(this.timeAmount)) {
            result.timeAmount = this.timeAmount.copy();
        }
        if (notNullOrUndefined(this.operator)) {
            result.operator = this.operator.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<TimeAmountPart>): boolean {
        let result: boolean = true;
        if (result && notNullOrUndefined(toBeMatched.timeAmount)) {
            result = result && this.timeAmount.match(toBeMatched.timeAmount);
        }
        if (result && notNullOrUndefined(toBeMatched.operator)) {
            result = result && this.operator.match(toBeMatched.operator);
        }
        return result;
    }

    /**
     * Convenience method for reference 'operator'.
     * Instead of returning a 'FreNodeReference<SimpleOperators>' object,
     * it returns the referred 'SimpleOperators' object, if it can be found.
     */
    get $operator(): SimpleOperators | undefined {
        if (!!this.operator) {
            return this.operator.referred;
        }
        return undefined;
    }
}
