// Generated by the Freon Language Generator.
// TEMPLATE: InterpreterBaseTemplate.interpreterBase(...)
// Will be overwritten with every generation.

import { InterpreterContext, RtObject, RtError } from "@freon4dsl/core";
import {
    ScheduleExpression,
    EventReferenceExpression,
    PeriodReferenceExpression,
    Time,
    PreviousVisit,
    StartDay,
    CountExpression,
    LiteralExpression,
    String,
    NumberLiteralExpression,
    BinaryExpression,
    MultiplyExpression,
    PlusExpression,
    MinusExpression,
    DivideExpression,
    AndExpression,
    OrExpression,
    ComparisonExpression,
    LessThenExpression,
    GreaterThenExpression,
    EqualsExpression,
    TimeExpression,
    PatientHistory,
    PatientVisitStatus,
    PatientVisit,
    PatientNotAvailable,
    StaffLevel,
    Month,
    VisitDate,
    DateRange,
    DateConcept,
    EventSchedule,
    EventReference,
    TimeUnit,
    PhaseState,
    EventState,
    SimpleOperators,
    Days,
    TimeAmount,
    TimeAmountPart,
    Day,
    When,
    StudyStart,
    FirstDayOfStudy,
    Baseline,
    Previous,
    Unscheduled,
    AnyDay,
    EventWindow,
    ComplianceWindow,
    ComplianceWindowOf,
    StartingBy,
    EndingBy,
    BetweenTimes,
    RepeatCondition,
    Daily,
    Weekly,
    Monthly,
    Forever,
    RepeatEvery,
    RepeatCount,
    Period,
    TypeOfEvent,
    Event,
    AbstractTask,
    EventTask,
    Task,
    SharedTask,
    TaskReference,
    Step,
    WorkflowDescription,
    WorkflowBranch,
    Description,
    AbstractSystemAccess,
    SystemAccess,
    SystemAccessReference,
    AccessedAtURL,
    AccessedAPhoneNumber,
    StaffRole,
    AbstractPerson,
    PersonReference,
    Person,
    Reference,
    RobotMapping,
    SourceToTargetMapping,
    Availability,
    PatientInfo,
    PatientHistoryUnit,
    StudyConfiguration,
} from "../language/index.js";

/**
 * The base class containing all interpreter functions that should be defined.
 * All functions throw an error when called.
 */
export class StudyConfigurationModelInterpreterBase {
    constructor() {}

    evalScheduleExpression(node: ScheduleExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalScheduleExpression is not defined");
    }

    evalEventReferenceExpression(node: EventReferenceExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEventReferenceExpression is not defined");
    }

    evalPeriodReferenceExpression(node: PeriodReferenceExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPeriodReferenceExpression is not defined");
    }

    evalTime(node: Time, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTime is not defined");
    }

    evalPreviousVisit(node: PreviousVisit, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPreviousVisit is not defined");
    }

    evalStartDay(node: StartDay, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStartDay is not defined");
    }

    evalCountExpression(node: CountExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalCountExpression is not defined");
    }

    evalLiteralExpression(node: LiteralExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalLiteralExpression is not defined");
    }

    evalString(node: String, ctx: InterpreterContext): RtObject {
        throw new RtError("evalString is not defined");
    }

    evalNumberLiteralExpression(node: NumberLiteralExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalNumberLiteralExpression is not defined");
    }

    evalBinaryExpression(node: BinaryExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalBinaryExpression is not defined");
    }

    evalMultiplyExpression(node: MultiplyExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalMultiplyExpression is not defined");
    }

    evalPlusExpression(node: PlusExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPlusExpression is not defined");
    }

    evalMinusExpression(node: MinusExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalMinusExpression is not defined");
    }

    evalDivideExpression(node: DivideExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDivideExpression is not defined");
    }

    evalAndExpression(node: AndExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAndExpression is not defined");
    }

    evalOrExpression(node: OrExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalOrExpression is not defined");
    }

    evalComparisonExpression(node: ComparisonExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalComparisonExpression is not defined");
    }

    evalLessThenExpression(node: LessThenExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalLessThenExpression is not defined");
    }

    evalGreaterThenExpression(node: GreaterThenExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalGreaterThenExpression is not defined");
    }

    evalEqualsExpression(node: EqualsExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEqualsExpression is not defined");
    }

    evalTimeExpression(node: TimeExpression, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTimeExpression is not defined");
    }

    evalPatientHistory(node: PatientHistory, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPatientHistory is not defined");
    }

    evalPatientVisitStatus(node: PatientVisitStatus, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPatientVisitStatus is not defined");
    }

    evalPatientVisit(node: PatientVisit, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPatientVisit is not defined");
    }

    evalPatientNotAvailable(node: PatientNotAvailable, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPatientNotAvailable is not defined");
    }

    evalStaffLevel(node: StaffLevel, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStaffLevel is not defined");
    }

    evalMonth(node: Month, ctx: InterpreterContext): RtObject {
        throw new RtError("evalMonth is not defined");
    }

    evalVisitDate(node: VisitDate, ctx: InterpreterContext): RtObject {
        throw new RtError("evalVisitDate is not defined");
    }

    evalDateRange(node: DateRange, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDateRange is not defined");
    }

    evalDateConcept(node: DateConcept, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDateConcept is not defined");
    }

    evalEventSchedule(node: EventSchedule, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEventSchedule is not defined");
    }

    evalEventReference(node: EventReference, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEventReference is not defined");
    }

    evalTimeUnit(node: TimeUnit, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTimeUnit is not defined");
    }

    evalPhaseState(node: PhaseState, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPhaseState is not defined");
    }

    evalEventState(node: EventState, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEventState is not defined");
    }

    evalSimpleOperators(node: SimpleOperators, ctx: InterpreterContext): RtObject {
        throw new RtError("evalSimpleOperators is not defined");
    }

    evalDays(node: Days, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDays is not defined");
    }

    evalTimeAmount(node: TimeAmount, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTimeAmount is not defined");
    }

    evalTimeAmountPart(node: TimeAmountPart, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTimeAmountPart is not defined");
    }

    evalDay(node: Day, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDay is not defined");
    }

    evalWhen(node: When, ctx: InterpreterContext): RtObject {
        throw new RtError("evalWhen is not defined");
    }

    evalStudyStart(node: StudyStart, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStudyStart is not defined");
    }

    evalFirstDayOfStudy(node: FirstDayOfStudy, ctx: InterpreterContext): RtObject {
        throw new RtError("evalFirstDayOfStudy is not defined");
    }

    evalBaseline(node: Baseline, ctx: InterpreterContext): RtObject {
        throw new RtError("evalBaseline is not defined");
    }

    evalPrevious(node: Previous, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPrevious is not defined");
    }

    evalUnscheduled(node: Unscheduled, ctx: InterpreterContext): RtObject {
        throw new RtError("evalUnscheduled is not defined");
    }

    evalAnyDay(node: AnyDay, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAnyDay is not defined");
    }

    evalEventWindow(node: EventWindow, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEventWindow is not defined");
    }

    evalComplianceWindow(node: ComplianceWindow, ctx: InterpreterContext): RtObject {
        throw new RtError("evalComplianceWindow is not defined");
    }

    evalComplianceWindowOf(node: ComplianceWindowOf, ctx: InterpreterContext): RtObject {
        throw new RtError("evalComplianceWindowOf is not defined");
    }

    evalStartingBy(node: StartingBy, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStartingBy is not defined");
    }

    evalEndingBy(node: EndingBy, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEndingBy is not defined");
    }

    evalBetweenTimes(node: BetweenTimes, ctx: InterpreterContext): RtObject {
        throw new RtError("evalBetweenTimes is not defined");
    }

    evalRepeatCondition(node: RepeatCondition, ctx: InterpreterContext): RtObject {
        throw new RtError("evalRepeatCondition is not defined");
    }

    evalDaily(node: Daily, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDaily is not defined");
    }

    evalWeekly(node: Weekly, ctx: InterpreterContext): RtObject {
        throw new RtError("evalWeekly is not defined");
    }

    evalMonthly(node: Monthly, ctx: InterpreterContext): RtObject {
        throw new RtError("evalMonthly is not defined");
    }

    evalForever(node: Forever, ctx: InterpreterContext): RtObject {
        throw new RtError("evalForever is not defined");
    }

    evalRepeatEvery(node: RepeatEvery, ctx: InterpreterContext): RtObject {
        throw new RtError("evalRepeatEvery is not defined");
    }

    evalRepeatCount(node: RepeatCount, ctx: InterpreterContext): RtObject {
        throw new RtError("evalRepeatCount is not defined");
    }

    evalPeriod(node: Period, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPeriod is not defined");
    }

    evalTypeOfEvent(node: TypeOfEvent, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTypeOfEvent is not defined");
    }

    evalEvent(node: Event, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEvent is not defined");
    }

    evalAbstractTask(node: AbstractTask, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAbstractTask is not defined");
    }

    evalEventTask(node: EventTask, ctx: InterpreterContext): RtObject {
        throw new RtError("evalEventTask is not defined");
    }

    evalTask(node: Task, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTask is not defined");
    }

    evalSharedTask(node: SharedTask, ctx: InterpreterContext): RtObject {
        throw new RtError("evalSharedTask is not defined");
    }

    evalTaskReference(node: TaskReference, ctx: InterpreterContext): RtObject {
        throw new RtError("evalTaskReference is not defined");
    }

    evalStep(node: Step, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStep is not defined");
    }

    evalWorkflowDescription(node: WorkflowDescription, ctx: InterpreterContext): RtObject {
        throw new RtError("evalWorkflowDescription is not defined");
    }

    evalWorkflowBranch(node: WorkflowBranch, ctx: InterpreterContext): RtObject {
        throw new RtError("evalWorkflowBranch is not defined");
    }

    evalDescription(node: Description, ctx: InterpreterContext): RtObject {
        throw new RtError("evalDescription is not defined");
    }

    evalAbstractSystemAccess(node: AbstractSystemAccess, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAbstractSystemAccess is not defined");
    }

    evalSystemAccess(node: SystemAccess, ctx: InterpreterContext): RtObject {
        throw new RtError("evalSystemAccess is not defined");
    }

    evalSystemAccessReference(node: SystemAccessReference, ctx: InterpreterContext): RtObject {
        throw new RtError("evalSystemAccessReference is not defined");
    }

    evalAccessedAtURL(node: AccessedAtURL, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAccessedAtURL is not defined");
    }

    evalAccessedAPhoneNumber(node: AccessedAPhoneNumber, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAccessedAPhoneNumber is not defined");
    }

    evalStaffRole(node: StaffRole, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStaffRole is not defined");
    }

    evalAbstractPerson(node: AbstractPerson, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAbstractPerson is not defined");
    }

    evalPersonReference(node: PersonReference, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPersonReference is not defined");
    }

    evalPerson(node: Person, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPerson is not defined");
    }

    evalReference(node: Reference, ctx: InterpreterContext): RtObject {
        throw new RtError("evalReference is not defined");
    }

    evalRobotMapping(node: RobotMapping, ctx: InterpreterContext): RtObject {
        throw new RtError("evalRobotMapping is not defined");
    }

    evalSourceToTargetMapping(node: SourceToTargetMapping, ctx: InterpreterContext): RtObject {
        throw new RtError("evalSourceToTargetMapping is not defined");
    }

    evalAvailability(node: Availability, ctx: InterpreterContext): RtObject {
        throw new RtError("evalAvailability is not defined");
    }

    evalPatientInfo(node: PatientInfo, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPatientInfo is not defined");
    }

    evalPatientHistoryUnit(node: PatientHistoryUnit, ctx: InterpreterContext): RtObject {
        throw new RtError("evalPatientHistoryUnit is not defined");
    }

    evalStudyConfiguration(node: StudyConfiguration, ctx: InterpreterContext): RtObject {
        throw new RtError("evalStudyConfiguration is not defined");
    }
}
