// Generated by the Freon Language Generator.
// TEMPLATE: GrammarModel.toMethod(...)

import { FreParseLocation, type FreNamedNode, type FreNode, FreNodeReference, type FreOwnerDescriptor } from "@freon4dsl/core";
import { StudyConfigurationModel } from "../language/index.js";

import {
    SyntaxAnalyserByMethodRegistrationAbstract,
    type KtList,
    type Sentence,
    type SpptDataNodeInfo,
    type SpptDataNode,
} from "net.akehurst.language-agl-processor";
import {
    AvailabilitySyntaxAnalyserPart,
    PatientInfoSyntaxAnalyserPart,
    PatientHistoryUnitSyntaxAnalyserPart,
    StudyConfigurationSyntaxAnalyserPart,
    StudyConfigurationModelCommonSyntaxAnalyserPart,
} from "./index.js";

export enum PrimValueType {
    "string",
    "identifier",
    "boolean",
    "number",
}

export class ParsedNodeReference implements FreNode {
    pathname: string[];
    parseLocation: FreParseLocation;

    constructor(pathname: string[], location: FreParseLocation) {
        this.pathname = pathname;
        this.parseLocation = location;
    }

    freId(): string {
        throw new Error("Method not implemented.");
    }
    freLanguageConcept(): string {
        throw new Error("Method not implemented.");
    }
    freOwner(): FreNode {
        throw new Error("Method not implemented.");
    }
    freOwnerDescriptor(): FreOwnerDescriptor {
        throw new Error("Method not implemented.");
    }
    freIsModel(): boolean {
        throw new Error("Method not implemented.");
    }
    freIsUnit(): boolean {
        throw new Error("Method not implemented.");
    }
    freIsExpression(): boolean {
        throw new Error("Method not implemented.");
    }
    freIsBinaryExpression(): boolean {
        throw new Error("Method not implemented.");
    }
    copy(): FreNode {
        throw new Error("Method not implemented.");
    }
    match(toBeMatched: Partial<FreNode>): boolean {
        throw new Error("Method not implemented.");
    }

    toString() {
        return `ParsedNodeReference: ${this.pathname} [${this.parseLocation.line}:${this.parseLocation.column}]`;
    }
}

/**
 *   Class StudyConfigurationModelSyntaxAnalyser is the main syntax analyser.
 *   The actual work is being done by its parts, one for each model unit,
 *   and one common part that contains the methods used in multiple units.
 *   Together the syntax analysers transform the parse tree into a FreNode model.
 *
 */
export class StudyConfigurationModelSyntaxAnalyser extends SyntaxAnalyserByMethodRegistrationAbstract<StudyConfigurationModel> {
    sourceName: string = "";
    private _unit_Availability_analyser: AvailabilitySyntaxAnalyserPart = new AvailabilitySyntaxAnalyserPart(this);
    private _unit_PatientInfo_analyser: PatientInfoSyntaxAnalyserPart = new PatientInfoSyntaxAnalyserPart(this);
    private _unit_PatientHistoryUnit_analyser: PatientHistoryUnitSyntaxAnalyserPart = new PatientHistoryUnitSyntaxAnalyserPart(this);
    private _unit_StudyConfiguration_analyser: StudyConfigurationSyntaxAnalyserPart = new StudyConfigurationSyntaxAnalyserPart(this);
    private _unit_common_analyser: StudyConfigurationModelCommonSyntaxAnalyserPart = new StudyConfigurationModelCommonSyntaxAnalyserPart(
        this,
    );

    registerHandlers() {
        super.registerFor("Availability", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_Availability_analyser.transformAvailability(n, c, s),
        );
        super.registerFor("StaffLevel", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_Availability_analyser.transformStaffLevel(n, c, s),
        );
        super.registerFor("PatientInfo", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_PatientInfo_analyser.transformPatientInfo(n, c, s),
        );
        super.registerFor("PatientHistoryUnit", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_PatientHistoryUnit_analyser.transformPatientHistoryUnit(n, c, s),
        );
        super.registerFor("StudyConfiguration", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformStudyConfiguration(n, c, s),
        );
        super.registerFor("Period", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPeriod(n, c, s),
        );
        super.registerFor("Description", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformDescription(n, c, s),
        );
        super.registerFor("Event", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEvent(n, c, s),
        );
        super.registerFor("Task", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTask(n, c, s),
        );
        super.registerFor("Step", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformStep(n, c, s),
        );
        super.registerFor("Reference", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformReference(n, c, s),
        );
        super.registerFor("PersonReference", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPersonReference(n, c, s),
        );
        super.registerFor("Person", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPerson(n, c, s),
        );
        super.registerFor("SystemAccess", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformSystemAccess(n, c, s),
        );
        super.registerFor("AccessedAtURL", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformAccessedAtURL(n, c, s),
        );
        super.registerFor("AccessedAPhoneNumber", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformAccessedAPhoneNumber(n, c, s),
        );
        super.registerFor("SystemAccessReference", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformSystemAccessReference(n, c, s),
        );
        super.registerFor("TaskReference", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTaskReference(n, c, s),
        );
        super.registerFor("EventSchedule", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventSchedule(n, c, s),
        );
        super.registerFor("Day", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformDay(n, c, s),
        );
        super.registerFor("TimeAmountPart", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTimeAmountPart(n, c, s),
        );
        super.registerFor("TimeAmount", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTimeAmount(n, c, s),
        );
        super.registerFor("When", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformWhen(n, c, s),
        );
        super.registerFor("EventReference", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventReference(n, c, s),
        );
        super.registerFor("StudyStart", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformStudyStart(n, c, s),
        );
        super.registerFor("FirstDayOfStudy", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformFirstDayOfStudy(n, c, s),
        );
        super.registerFor("Baseline", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformBaseline(n, c, s),
        );
        super.registerFor("Previous", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPrevious(n, c, s),
        );
        super.registerFor("Unscheduled", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformUnscheduled(n, c, s),
        );
        super.registerFor("AnyDay", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformAnyDay(n, c, s),
        );
        super.registerFor("EventWindow", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventWindow(n, c, s),
        );
        super.registerFor("Days", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformDays(n, c, s),
        );
        super.registerFor("ComplianceWindowOf", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformComplianceWindowOf(n, c, s),
        );
        super.registerFor("RepeatCondition", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformRepeatCondition(n, c, s),
        );
        super.registerFor("Daily", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformDaily(n, c, s),
        );
        super.registerFor("Weekly", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformWeekly(n, c, s),
        );
        super.registerFor("Monthly", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformMonthly(n, c, s),
        );
        super.registerFor("Forever", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformForever(n, c, s),
        );
        super.registerFor("RepeatEvery", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformRepeatEvery(n, c, s),
        );
        super.registerFor("Time", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTime(n, c, s),
        );
        super.registerFor("EventReferenceExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventReferenceExpression(n, c, s),
        );
        super.registerFor("PeriodReferenceExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPeriodReferenceExpression(n, c, s),
        );
        super.registerFor("PreviousVisit", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPreviousVisit(n, c, s),
        );
        super.registerFor("StartDay", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformStartDay(n, c, s),
        );
        super.registerFor("CountExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformCountExpression(n, c, s),
        );
        super.registerFor("NumberLiteralExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformNumberLiteralExpression(n, c, s),
        );
        super.registerFor("RepeatCount", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformRepeatCount(n, c, s),
        );
        super.registerFor("StartingBy", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformStartingBy(n, c, s),
        );
        super.registerFor("EndingBy", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEndingBy(n, c, s),
        );
        super.registerFor("BetweenTimes", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformBetweenTimes(n, c, s),
        );
        super.registerFor("SharedTask", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformSharedTask(n, c, s),
        );
        super.registerFor("StaffRole", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformStaffRole(n, c, s),
        );
        super.registerFor("EventTask", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventTask(n, c, s),
        );
        super.registerFor("AbstractPerson", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformAbstractPerson(n, c, s),
        );
        super.registerFor("AbstractSystemAccess", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformAbstractSystemAccess(n, c, s),
        );
        super.registerFor("AccessedAt", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformAccessedAt(n, c, s),
        );
        super.registerFor("EventStart", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventStart(n, c, s),
        );
        super.registerFor("ComplianceWindow", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformComplianceWindow(n, c, s),
        );
        super.registerFor("RepeatExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformRepeatExpression(n, c, s),
        );
        super.registerFor("RepeatUnit", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformRepeatUnit(n, c, s),
        );
        super.registerFor("ScheduleExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformScheduleExpression(n, c, s),
        );
        super.registerFor("LiteralExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformLiteralExpression(n, c, s),
        );
        super.registerFor("EventTimeOfDay", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventTimeOfDay(n, c, s),
        );
        super.registerFor("__fre_super_FirstDayOfStudy", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transform__fre_super_FirstDayOfStudy(n, c, s),
        );
        super.registerFor("__fre_super_Unscheduled", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transform__fre_super_Unscheduled(n, c, s),
        );
        super.registerFor("__fre_binary_ScheduleExpression", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transform__fre_binary_ScheduleExpression(n, c, s),
        );
        super.registerFor("TimeUnit", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTimeUnit(n, c, s),
        );
        super.registerFor("SimpleOperators", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformSimpleOperators(n, c, s),
        );
        super.registerFor("EventState", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformEventState(n, c, s),
        );
        super.registerFor("PhaseState", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformPhaseState(n, c, s),
        );
        super.registerFor("TypeOfEvent", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_StudyConfiguration_analyser.transformTypeOfEvent(n, c, s),
        );
        super.registerFor("DateConcept", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_common_analyser.transformDateConcept(n, c, s),
        );
        super.registerFor("DateRange", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_common_analyser.transformDateRange(n, c, s),
        );
        super.registerFor("PatientHistory", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_common_analyser.transformPatientHistory(n, c, s),
        );
        super.registerFor("PatientVisit", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_common_analyser.transformPatientVisit(n, c, s),
        );
        super.registerFor("Month", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_common_analyser.transformMonth(n, c, s),
        );
        super.registerFor("PatientVisitStatus", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this._unit_common_analyser.transformPatientVisitStatus(n, c, s),
        );
        super.registerFor("__fre_reference", (n: SpptDataNodeInfo, c: KtList<object>, s: Sentence) =>
            this.transform__fre_reference(n, c, s),
        );
    }

    /**
     * Generic method to transform lists of primitive values
     */
    public transformPrimList<T extends string | number | boolean>(list: string[], primType: PrimValueType, separator?: string): T[] {
        // console.log("transformPrimList called: "  + JSON.stringify(list));
        let result: T[] = [];
        if (!!list) {
            list.forEach((element) => {
                if (element !== null && element !== undefined && element !== separator) {
                    result.push(this.transformPrimValue(element, primType) as T);
                }
            });
        }
        return result;
    }

    /**
     * Generic method to transform a primitive value, which is parsed as a string, into the correct type.
     */
    public transformPrimValue<T extends string | number | boolean>(element: string, primType: PrimValueType): T {
        // console.log("transformPrimValue called: " + element + ", " + primType);
        switch (primType) {
            case PrimValueType.number:
                const num = parseFloat(element);
                return (isNaN(num) ? 0 : num) as T; // Handle invalid number gracefully.
            case PrimValueType.string:
                // todo make sure we remove only the outer quotes
                return element.replace(/"/g, "") as T;
            case PrimValueType.identifier:
                // todo make sure we remove only the outer quotes
                return element.replace(/`/g, "") as T;
            case PrimValueType.boolean:
                return (element.toLowerCase() === "true") as T; // Case-insensitive matching for booleans.
            default:
                return element as T; // Default case (string)
        }
    }

    /**
     * Generic method to transform lists of parts.
     */
    public transformPartList<T>(list: KtList<T>, separator?: string): T[] {
        // console.log("transformPartList called: " + JSON.stringify(list));
        let result: T[] = [];
        if (!!list) {
            for (const element of list.asJsReadonlyArrayView()) {
                if (element !== null && element !== undefined && element !== separator) {
                    result.push(element);
                }
            }
        }
        return result;
    }

    /**
     * Generic method to transform lists of references. The input will be a list of ParsedNodeReferences, which
     * result from transform__fre_reference. However, the input may also contain objects of type String,
     * which hold the separator between the elements of the reference list, not the 'reference separator' (".").
     */
    public transformRefList<T extends FreNamedNode>(list: KtList<T>, typeName: string): FreNodeReference<T>[] {
        // console.log("transformRefList called: " + JSON.stringify(list));
        let result: FreNodeReference<T>[] = [];
        if (!!list) {
            for (const child of list.asJsReadonlyArrayView()) {
                if (child.constructor.name === "ParsedNodeReference") {
                    result.push(this.makeFreNodeRef<T>(child as unknown as ParsedNodeReference, typeName));
                }
            }
        }
        return result;
    }

    /**
     * Generic method to transform a single reference into a temporary object of type ParsedNodeReference.
     * The actual FreNodeReference object is created when the type of the referred node is known.
     * The 'reference separator' (".") is removed in the process.
     */
    public transform__fre_reference(nodeInfo: SpptDataNodeInfo, children: KtList<object>, sentence: Sentence): ParsedNodeReference {
        let pathname: string[] = [];
        for (const child of children.asJsReadonlyArrayView()) {
            if (child !== null && child !== undefined && (typeof child === "string" ? child !== "." : false)) {
                // todo make sure we remove only the outer quotes
                const name = child.toString().replace(/`/g, "");
                pathname.push(name);
            }
        }
        return new ParsedNodeReference(pathname, this.location(sentence, nodeInfo.node));
    }

    /**
     * Generic method to transform a ParsedNodeReference into the right FreNodeReference.
     *
     * @param referred
     * @param freMetaConcept
     */
    public makeFreNodeRef<T extends FreNamedNode>(referred: ParsedNodeReference, freMetaConcept: string): FreNodeReference<T> {
        const result = FreNodeReference.create<T>(referred.pathname, freMetaConcept);
        result.parseLocation = (referred as ParsedNodeReference).parseLocation;
        return result;
    }

    /**
     * Generic method to transform a list of references to limited objects into the correct list. The input may have
     * elements of type String, which represent the separators, terminators, etc. These elements are ignored.
     *
     * @param list
     * @private
     */
    public transformLimitedList<T extends FreNamedNode>(list: KtList<any>): FreNodeReference<T>[] {
        let result: FreNodeReference<T>[] = [];
        list.asJsReadonlyArrayView().forEach((xx) => {
            if (xx instanceof FreNodeReference) {
                result.push(xx);
            }
        });
        return result;
    }

    /**
     * Generic method to transform location information.
     *
     * @param sentence
     * @param node
     */
    public location(sentence: Sentence, node: SpptDataNode): FreParseLocation {
        const location = sentence.locationFor(node.startPosition, node.nextInputNoSkip - node.startPosition);
        return FreParseLocation.create({
            filename: this.sourceName,
            line: location.line,
            column: location.column,
        });
    }
}
