// Generated by the Freon Language Generator.
// This file contains the input to the AGL parser generator
// (see https://https://github.com/dhakehurst/net.akehurst.language).
// The grammar in this file is read by StudyConfigurationModelModelUnitReader

export const StudyConfigurationModelGrammarStr = `
namespace StudyConfigurationModelLanguage
grammar StudyConfigurationModelGrammar {

// rules for "Availability"
Availability = 'STAFFING'
	 'Number' 'of' 'CRCs' 'Normally' 'Available:' stringLiteral
	 'Staffing' 'Level' 'Changes:'
	 StaffLevel* ;

StaffLevel = stringLiteral 'on:' DateRange ;

// rules for "PatientInfo"
PatientInfo = 'Patient' 'Histories:'
	 PatientHistory* ;

// rules for "PatientHistoryUnit"
PatientHistoryUnit = PatientHistory ;

// rules for "StudyConfiguration"
StudyConfiguration = 'Periods:'
	 Period*
	 'Tasks:'
	 SharedTask*
	 'System' 'Accesses:'
	 SystemAccess*
	 'Staffing:'
	 Person*
	 'Roles:'
	 StaffRole* ;

Period = 'Period:' identifier
	 Description
	 'Events:'
	 Event* ;

Description = ( 'Description:' stringLiteral )? ;

Event = 'Event:' identifier
	 'This' 'is' 'a' TypeOfEvent ( 'that' 'is' 'also' 'referred' 'to' 'as' stringLiteral )?
	 Description
	 'Schedule:'
	 EventSchedule
	 'Tasks:'
	 EventTask* ;

Task = 'Task:' identifier
	 Description?
	 'Steps:'
	 Step* ;

Step = 'Step:' identifier
	 Description?
	 'People:'
	 AbstractPerson*
	 'Systems' 'Used:'
	 AbstractSystemAccess*
	 'References:'
	 Reference* ;

Reference = 'Reference:' stringLiteral
	 'Document' 'is' 'at:' optStringLiteral
	 Description? ;

PersonReference = 'PersonReference:' __fre_reference ;

Person = 'Name:' identifier
	 'Email:' optStringLiteral
	 'Phone:' optStringLiteral
	 'Role:' __fre_reference
	 'Notes:' Description? ;

SystemAccess = 'System' 'Name:' identifier
	 'Accessed' 'At:' AccessedAt
	 Description? ;

AccessedAtURL = 'URL:' optStringLiteral ;

AccessedAPhoneNumber = 'Phone' 'Number:' optStringLiteral ;

SystemAccessReference = 'SystemAccessReference:' __fre_reference ;

TaskReference = 'TaskReference:' __fre_reference ;

EventSchedule = 'First' 'scheduled' EventStart
	 EventWindow?
	 ( 'and' 'then' 'repeats' RepeatExpression )?
	 ( 'limited' 'to' EventTimeOfDay )? ;

Day = 'day' numberLiteral ;

TimeAmountPart = SimpleOperators TimeAmount ;

TimeAmount = numberLiteral TimeUnit ;

When = 'when' EventReference TimeAmountPart? ;

EventReference = __fre_reference EventState ;

StudyStart = optStringLiteral 'as' 'the' 'start' 'day' 'of' 'the' 'study' ;

FirstDayOfStudy = 'on' 'the' 'start' 'day' 'of' 'the' 'study' TimeAmountPart? ;

Baseline = 'on' 'the' 'baseline\/start' 'day' 'of' 'the' 'study' TimeAmountPart? ;

Previous = 'when' 'the' 'previous' 'event' EventState TimeAmountPart? ;

Unscheduled = 'on' 'any' 'day' '(an' 'unscheduled' 'event)' ;

AnyDay = 'on' 'any' 'day' '(an' 'unscheduled' 'event)' ;

EventWindow = 'with' 'a' 'window' 'of' Days 'day(s)' 'before' 'and' Days 'day(s)' 'after'
	 ComplianceWindow? ;

Days = numberLiteral ;

ComplianceWindowOf = 'and' 'a' 'compliance' 'window' 'of' Days 'additional' 'day(s)' 'before' 'and' Days 'day(s)' 'after' ;

RepeatCondition = RepeatUnit ( 'up' 'to' numberLiteral 'times' )?
	 ( 'until' ScheduleExpression )? ;

Daily = 'daily' ;

Weekly = 'weekly' ;

Monthly = 'monthly' ;

Forever = 'forever' ;

RepeatEvery = 'every:' Time ;

Time = stringLiteral TimeUnit ;

EventReferenceExpression = __fre_reference EventState ;

PeriodReferenceExpression = __fre_reference PhaseState ;

PreviousVisit = 'previous' 'visit' ;

StartDay = 'start' 'day' ;

CountExpression = 'count(' __fre_reference ')' ;

NumberLiteralExpression = numberLiteral ;

RepeatCount = numberLiteral 'time(s)' ;

StartingBy = 'starting' 'by' stringLiteral ;

EndingBy = 'ending' 'by' stringLiteral ;

BetweenTimes = 'starting' 'by' stringLiteral 'and' 'ending' 'by' stringLiteral ;

SharedTask = 'Shared' 'Task:' identifier
	 Description?
	 'Steps:'
	 Step* ;

StaffRole = 'Role:' identifier
	 Description? ;

EventTask = TaskReference 
    | Task  ;

AbstractPerson = PersonReference 
    | Person  ;

AbstractSystemAccess = SystemAccessReference 
    | SystemAccess  ;

AccessedAt = AccessedAtURL 
    | AccessedAPhoneNumber  ;

EventStart = When 
    | __fre_super_FirstDayOfStudy 
    | Previous 
    | __fre_super_Unscheduled 
    | Day 
    | StudyStart  ;

ComplianceWindow = ComplianceWindowOf  ;

RepeatExpression = RepeatCondition 
    | RepeatCount  ;

RepeatUnit = Daily 
    | Weekly 
    | Monthly 
    | Forever 
    | RepeatEvery  ;

ScheduleExpression = EventReferenceExpression 
    | PeriodReferenceExpression 
    | PreviousVisit 
    | StartDay 
    | CountExpression 
    | LiteralExpression 
    | Time 
    | __fre_binary_ScheduleExpression ;

LiteralExpression = NumberLiteralExpression  ;

EventTimeOfDay = StartingBy 
    | EndingBy 
    | BetweenTimes  ;

__fre_super_FirstDayOfStudy = FirstDayOfStudy 
    | Baseline  ;

__fre_super_Unscheduled = Unscheduled 
    | AnyDay  ;

__fre_binary_ScheduleExpression = [ScheduleExpression / __fre_binary_operator]2+ ;
leaf __fre_binary_operator = 'and' | 'or' | '==' | '*' | '+' | '-' | '/' | '<' | '>' ;

TimeUnit = '\`hours\`'
	| '\`days\`'
	| '\`weeks\`'
	| '\`months\`' ;

SimpleOperators = '\`+\`'
	| '\`-\`' ;

EventState = '\`completed\`'
	| '\`each completed\`'
	| '\`started\`'
	| '\`scheduled\`'
	| '\`skipped\`' ;

PhaseState = '\`completed\`'
	| '\`started\`'
	| '\`skipped\`' ;

TypeOfEvent = '\`site visit\`'
	| '\`preparation\`'
	| '\`video session\`'
	| '\`phone call\`'
	| '\`non-standard\`' ;

// common rules
DateConcept = stringLiteral ;

DateRange = DateConcept 'thru:' DateConcept? ;

PatientHistory = 'Patient' 'ID:' stringLiteral
	 'Visits:'
	 PatientVisit*
	 'Not' 'Available' 'Dates:'
	 DateRange* ;

PatientVisit = 'Visit:' __fre_reference 'was' PatientVisitStatus 'on' DateConcept ;

Month = '\`January\`'
	| '\`February\`'
	| '\`March\`'
	| '\`April\`'
	| '\`May\`'
	| '\`June\`'
	| '\`July\`'
	| '\`August\`'
	| '\`September\`'
	| '\`October\`'
	| '\`November\`'
	| '\`December\`' ;

PatientVisitStatus = '\`planned\`'
	| '\`completed\`'
	| '\`missed\`'
	| '\`canceled\`' ;

__fre_reference = [ identifier / '.' ]+ ;

// white space and comments
skip WHITE_SPACE = "\\s+" ;
skip SINGLE_LINE_COMMENT = "//[^\\r\\n]*" ;
skip MULTI_LINE_COMMENT = "/\\*[^*]*\\*+(?:[^*/][^*]*\\*+)*/" ;

// the predefined basic types
leaf identifier        = "\`[a-zA-Z0-9-_~!@#$%^&*()+={\\[}\\]|\:;\\"'<>,.?/][a-zA-Z0-9-_~!@#$%^&*()\\\\+={\\[}\\]|\:;\\"'<>,.?/ ]*\`" ;
/* see https://stackoverflow.com/questions/37032620/regex-for-matching-a-string-literal-in-java */
leaf optStringLiteral  = "<no-value>" | stringLiteral ;
leaf stringLiteral     = '"' "[^\\"\\\\]*(\\\\.[^\\"\\\\]*)*" '"' ;
leaf optNumberLiteral  = "<no-value>" | numberLiteral;
leaf numberLiteral     = "[0-9]+";
leaf optBooleanLiteral = "<no-value>" | booleanLiteral;
leaf booleanLiteral    = 'false' | 'true';

}`; // end of grammar
