// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { UndoModelDefaultWorker } from "../utils/gen/UndoModelDefaultWorker.js";
import { UndoModelCheckerInterface } from "./gen/UndoModelValidator.js";

export class CustomUndoModelValidator extends UndoModelDefaultWorker implements UndoModelCheckerInterface {
    errorList: FreError[] = [];
}
