// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { InsuranceModelDefaultWorker } from "../utils/gen/InsuranceModelDefaultWorker.js";
import { InsuranceModelCheckerInterface } from "./gen/InsuranceModelValidator.js";

export class CustomInsuranceModelValidator extends InsuranceModelDefaultWorker implements InsuranceModelCheckerInterface {
    errorList: FreError[] = [];
}
