/**
 * Script to read JSON files from studies folders and generate SQL UPDATE statements
 * Run with: node packages/server-crchub/database/generate_json_updates.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const datastorePath = path.join(__dirname, '../datastore');
const studiesPath = path.join(datastorePath, 'studies');
const outputPath = path.join(__dirname, 'load_json_updates.sql');

// Studies that exist in the database (from seed_studies_and_patients.sql)
const validStudyIds = new Set([
  'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  'e0b1dc36-07ee-4f0f-8ba6-8d9c69724c67',
  '46abda0c-51c3-473a-ad01-dacbc03d8639',
  '7e010ccb-0eee-405c-8ebb-8beb162c7b59',
  '024c3afb-0d38-438c-af3c-08b8be9f7d1d',
  '65a6658b-5772-4ee9-a139-4fd7c792291a',
  '5069dcf5-efea-429c-bc23-1d934fa5b7a9',
  '19e0d795-364e-49cf-aa09-f5ee808b4743',
  '0477e3f5-7c2e-45b8-a09c-d638f229d6bd',
  '456d72ce-da14-48b7-ba88-55b2cc9d9158',
  '53d865c0-be17-4d82-b1e6-5d4be9fe5e01',
  'c134550f-359a-4254-829b-7b141340b403',
  '3a7e9f8b-1c2d-4e5f-9e8b-6a7b8c9d0e1f', // MK-3475-028 from patients.json
]);

function escapeJsonForSql(jsonString) {
  // Use dollar-quoting for safer JSON handling in PostgreSQL
  // This avoids escaping issues with quotes, backslashes, etc.
  return jsonString;
}

function generateUpdates() {
  const updates = [];
  updates.push('-- Generated SQL UPDATE statements for loading JSON files');
  updates.push('-- Generated by generate_json_updates.js');
  updates.push('');
  updates.push('BEGIN;');
  updates.push('');

  // Read all study folders
  const studyFolders = fs.readdirSync(studiesPath, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);

  const studyFiles = [];

  // Collect all JSON files for valid studies
  for (const folder of studyFolders) {
    if (!validStudyIds.has(folder)) {
      console.log(`Skipping study folder ${folder} - not in database`);
      continue;
    }

    const studyFolderPath = path.join(studiesPath, folder);
    const files = { studyId: folder };

    // Check for StudyConfiguration.json
    const studyConfigPath = path.join(studyFolderPath, 'StudyConfiguration.json');
    if (fs.existsSync(studyConfigPath)) {
      files.studyConfiguration = fs.readFileSync(studyConfigPath, 'utf-8');
      console.log(`Found StudyConfiguration.json for ${folder}`);
    }

    // Check for Availability.json
    const availabilityPath = path.join(studyFolderPath, 'Availability.json');
    if (fs.existsSync(availabilityPath)) {
      files.availability = fs.readFileSync(availabilityPath, 'utf-8');
      console.log(`Found Availability.json for ${folder}`);
    }

    // Check for PatientInfo.json
    const patientInfoPath = path.join(studyFolderPath, 'PatientInfo.json');
    if (fs.existsSync(patientInfoPath)) {
      files.patientInfo = fs.readFileSync(patientInfoPath, 'utf-8');
      console.log(`Found PatientInfo.json for ${folder}`);
    }

    studyFiles.push(files);
  }

  // Generate UPDATE statements for StudyConfiguration.json
  updates.push('-- ============================================================================');
  updates.push('-- UPDATE site_protocol_versions.study_configuration');
  updates.push('-- ============================================================================');
  updates.push('');

  for (const study of studyFiles) {
    if (study.studyConfiguration) {
      const jsonContent = escapeJsonForSql(study.studyConfiguration);
      const dollarTag = `json_${study.studyId.replace(/-/g, '_')}`;
      updates.push(`-- Study: ${study.studyId}`);
      updates.push(`UPDATE site_protocol_versions`);
      updates.push(`SET study_configuration = $${dollarTag}$`);
      updates.push(jsonContent);
      updates.push(`$${dollarTag}$::jsonb`);
      updates.push(`WHERE site_protocol_id IN (`);
      updates.push(`    SELECT spv.site_protocol_id`);
      updates.push(`    FROM site_protocol_versions spv`);
      updates.push(`    JOIN site s ON spv.site_id = s.site_id`);
      updates.push(`    JOIN protocol_version pv ON spv.protocol_version_id = pv.protocol_version_id`);
      updates.push(`    JOIN protocol p ON pv.protocol_id = p.protocol_id`);
      updates.push(`    WHERE p.study_id = '${study.studyId}'::uuid`);
      updates.push(`    ORDER BY spv.created_at DESC`);
      updates.push(`    LIMIT 1`);
      updates.push(`);`);
      updates.push('');
    }
  }

  // Generate UPDATE statements for PatientInfo.json
  updates.push('-- ============================================================================');
  updates.push('-- UPDATE site.patient_availability_and_history');
  updates.push('-- ============================================================================');
  updates.push('');

  for (const study of studyFiles) {
    if (study.patientInfo) {
      const jsonContent = escapeJsonForSql(study.patientInfo);
      const dollarTag = `json_${study.studyId.replace(/-/g, '_')}_patient`;
      updates.push(`-- Study: ${study.studyId}`);
      updates.push(`UPDATE site`);
      updates.push(`SET patient_availability_and_history = $${dollarTag}$`);
      updates.push(jsonContent);
      updates.push(`$${dollarTag}$::jsonb`);
      updates.push(`WHERE site_id IN (`);
      updates.push(`    SELECT s.site_id`);
      updates.push(`    FROM site s`);
      updates.push(`    JOIN protocol_version pv ON s.protocol_version_id = pv.protocol_version_id`);
      updates.push(`    JOIN protocol p ON pv.protocol_id = p.protocol_id`);
      updates.push(`    WHERE p.study_id = '${study.studyId}'::uuid`);
      updates.push(`);`);
      updates.push('');
    }
  }

  // Generate UPDATE statements for Availability.json
  updates.push('-- ============================================================================');
  updates.push('-- UPDATE organization.staff_availability');
  updates.push('-- ============================================================================');
  updates.push('');

  for (const study of studyFiles) {
    if (study.availability) {
      const jsonContent = escapeJsonForSql(study.availability);
      const dollarTag = `json_${study.studyId.replace(/-/g, '_')}_avail`;
      updates.push(`-- Study: ${study.studyId}`);
      updates.push(`UPDATE organization`);
      updates.push(`SET staff_availability = $${dollarTag}$`);
      updates.push(jsonContent);
      updates.push(`$${dollarTag}$::jsonb`);
      updates.push(`WHERE org_id IN (`);
      updates.push(`    SELECT DISTINCT o.org_id`);
      updates.push(`    FROM organization o`);
      updates.push(`    JOIN org_study_roles osr ON o.org_id = osr.org_id`);
      updates.push(`    WHERE osr.study_id = '${study.studyId}'::uuid`);
      updates.push(`);`);
      updates.push('');
    }
  }

  updates.push('COMMIT;');
  updates.push('');

  return updates.join('\n');
}

// Main execution
try {
  const sql = generateUpdates();
  fs.writeFileSync(outputPath, sql, 'utf-8');
  console.log(`✅ Generated SQL file: ${outputPath}`);
  console.log(`📝 Review the file and run it against your database`);
} catch (error) {
  console.error('❌ Error generating SQL:', error);
  process.exit(1);
}

