// Generated by the Freon Language Generator.
import { FreError, FreErrorSeverity } from "@freon4dsl/core";
import { OctopusModelDefaultWorker } from "../utils/gen/OctopusModelDefaultWorker.js";
import { OctopusModelCheckerInterface } from "./gen/OctopusModelValidator.js";

export class CustomOctopusModelValidator extends OctopusModelDefaultWorker implements OctopusModelCheckerInterface {
    errorList: FreError[] = [];
}
