// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import { MobxModelElementImpl, observablepart, type FreNode, FreParseLocation, notNullOrUndefined, FreUtils } from "@freon4dsl/core";
import { Days, ComplianceWindow } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class EventWindow is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class EventWindow extends MobxModelElementImpl implements FreNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<EventWindow>): EventWindow {
        const result = new EventWindow(data.$id);
        if (notNullOrUndefined(data.daysBefore)) {
            result.daysBefore = data.daysBefore;
        } else {
            result.daysBefore = Days.create({});
        }
        if (notNullOrUndefined(data.daysAfter)) {
            result.daysAfter = data.daysAfter;
        } else {
            result.daysAfter = Days.create({});
        }
        if (notNullOrUndefined(data.complianceWindow)) {
            result.complianceWindow = data.complianceWindow;
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "EventWindow"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed

    daysBefore!: Days; // implementation of part 'daysBefore'
    daysAfter!: Days; // implementation of part 'daysAfter'
    complianceWindow: ComplianceWindow | undefined; // implementation of part 'complianceWindow'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "daysBefore");

        observablepart(this, "daysAfter");

        observablepart(this, "complianceWindow");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): EventWindow {
        const result = new EventWindow();
        if (notNullOrUndefined(this.daysBefore)) {
            result.daysBefore = this.daysBefore.copy();
        }
        if (notNullOrUndefined(this.daysAfter)) {
            result.daysAfter = this.daysAfter.copy();
        }
        if (notNullOrUndefined(this.complianceWindow)) {
            result.complianceWindow = this.complianceWindow.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<EventWindow>): boolean {
        let result: boolean = true;
        if (result && notNullOrUndefined(toBeMatched.daysBefore)) {
            result = result && this.daysBefore.match(toBeMatched.daysBefore);
        }
        if (result && notNullOrUndefined(toBeMatched.daysAfter)) {
            result = result && this.daysAfter.match(toBeMatched.daysAfter);
        }
        if (result && notNullOrUndefined(toBeMatched.complianceWindow)) {
            if (this.complianceWindow) {
                result = result && this.complianceWindow.match(toBeMatched.complianceWindow);
            }
        }
        return result;
    }
}
