// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import {
    MobxModelElementImpl,
    observableprim,
    observablepart,
    type FreNamedNode,
    FreParseLocation,
    notNullOrUndefined,
    FreNodeReference,
    FreUtils,
} from "@freon4dsl/core";
import { DateConcept, Event, PatientVisitStatus } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class PatientVisit is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class PatientVisit extends MobxModelElementImpl implements FreNamedNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<PatientVisit>): PatientVisit {
        const result = new PatientVisit(data.$id);
        if (notNullOrUndefined(data.name)) {
            result.name = data.name;
        }
        if (notNullOrUndefined(data.visitInstanceNumber)) {
            result.visitInstanceNumber = data.visitInstanceNumber;
        }
        if (notNullOrUndefined(data.actualVisitDate)) {
            result.actualVisitDate = data.actualVisitDate;
        } else {
            result.actualVisitDate = DateConcept.create({});
        }
        if (notNullOrUndefined(data.visit)) {
            result.visit = data.visit;
        }
        if (notNullOrUndefined(data.status)) {
            result.status = data.status;
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "PatientVisit"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    name!: string; // implementation of name
    visitInstanceNumber!: number; // implementation of visitInstanceNumber
    actualVisitDate!: DateConcept; // implementation of part 'actualVisitDate'
    visit!: FreNodeReference<Event>; // implementation of reference 'visit'
    status!: FreNodeReference<PatientVisitStatus>; // implementation of reference 'status'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, "name");
        this.name = "";
        observableprim(this, "visitInstanceNumber");
        this.visitInstanceNumber = 1;

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepart(this, "actualVisitDate");

        observablepart(this, "visit");

        observablepart(this, "status");
        this.status = FreNodeReference.create<PatientVisitStatus>(PatientVisitStatus.planned, "PatientVisitStatus");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): PatientVisit {
        const result = new PatientVisit();
        if (notNullOrUndefined(this.name)) {
            result.name = this.name;
        }
        if (notNullOrUndefined(this.visitInstanceNumber)) {
            result.visitInstanceNumber = this.visitInstanceNumber;
        }
        if (notNullOrUndefined(this.actualVisitDate)) {
            result.actualVisitDate = this.actualVisitDate.copy();
        }
        if (notNullOrUndefined(this.visit)) {
            result.visit = this.visit.copy();
        }
        if (notNullOrUndefined(this.status)) {
            result.status = this.status.copy();
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<PatientVisit>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && toBeMatched.visitInstanceNumber !== null && toBeMatched.visitInstanceNumber !== undefined) {
            result = result && this.visitInstanceNumber === toBeMatched.visitInstanceNumber;
        }
        if (result && notNullOrUndefined(toBeMatched.actualVisitDate)) {
            result = result && this.actualVisitDate.match(toBeMatched.actualVisitDate);
        }
        if (result && notNullOrUndefined(toBeMatched.visit)) {
            result = result && this.visit.match(toBeMatched.visit);
        }
        if (result && notNullOrUndefined(toBeMatched.status)) {
            result = result && this.status.match(toBeMatched.status);
        }
        return result;
    }

    /**
     * Convenience method for reference 'visit'.
     * Instead of returning a 'FreNodeReference<Event>' object,
     * it returns the referred 'Event' object, if it can be found.
     */
    get $visit(): Event | undefined {
        if (!!this.visit) {
            return this.visit.referred;
        }
        return undefined;
    }
    /**
     * Convenience method for reference 'status'.
     * Instead of returning a 'FreNodeReference<PatientVisitStatus>' object,
     * it returns the referred 'PatientVisitStatus' object, if it can be found.
     */
    get $status(): PatientVisitStatus | undefined {
        if (!!this.status) {
            return this.status.referred;
        }
        return undefined;
    }
}
