// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import { type FreExpressionNode, FreParseLocation, notNullOrUndefined } from "@freon4dsl/core";
import { ScheduleExpression } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate

/**
 * Class PreviousVisit is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class PreviousVisit extends ScheduleExpression implements FreExpressionNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<PreviousVisit>): PreviousVisit {
        const result = new PreviousVisit(data.$id);

        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "PreviousVisit"; // holds the metatype in the form of a string

    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed

    constructor(id?: string) {
        super(id);
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return true;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): PreviousVisit {
        const result = new PreviousVisit();

        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<PreviousVisit>): boolean {
        let result: boolean = super.match(toBeMatched);

        return result;
    }
}
