// Generated by the Freon Language Generator.
// TEMPLATE ConceptTemplate.generateConceptPrivate(...)

import {
    MobxModelElementImpl,
    observableprim,
    observablepartlist,
    type FreNamedNode,
    FreParseLocation,
    notNullOrUndefined,
    FreUtils,
    matchElementList,
} from "@freon4dsl/core";
import { SourceToTargetMapping } from "./internal.js";

// TEMPLATE: ConceptTemplate.generateConceptPrivate
import { makeObservable, action } from "mobx";

/**
 * Class RobotMapping is the implementation of the concept with the same name in the language definition file.
 * It uses mobx decorators to enable parts of the language environment, e.g. the editor, to react
 * to the changes in the state of its properties.
 */
export class RobotMapping extends MobxModelElementImpl implements FreNamedNode {
    /**
     * A convenience method that creates an instance of this class
     * based on the properties defined in 'data'.
     * @param data partial object
     */
    static create(data: Partial<RobotMapping>): RobotMapping {
        const result = new RobotMapping(data.$id);
        if (notNullOrUndefined(data.name)) {
            result.name = data.name;
        }
        if (notNullOrUndefined(data.sourcePage)) {
            result.sourcePage = data.sourcePage;
        }
        if (notNullOrUndefined(data.targetPage)) {
            result.targetPage = data.targetPage;
        }
        if (notNullOrUndefined(data.closeSource)) {
            result.closeSource = data.closeSource;
        }
        if (notNullOrUndefined(data.sourceToTargetMappings)) {
            data.sourceToTargetMappings.forEach((x) => result.sourceToTargetMappings.push(x));
        }
        if (notNullOrUndefined(data.parseLocation)) {
            result.parseLocation = data.parseLocation;
        }
        return result;
    }

    readonly $typename: string = "RobotMapping"; // holds the metatype in the form of a string
    $id: string = ""; // a unique identifier
    parseLocation: FreParseLocation | undefined; // if relevant, the location of this element within the source from which it is parsed
    name!: string; // implementation of name
    sourcePage!: string; // implementation of sourcePage
    targetPage!: string; // implementation of targetPage
    closeSource!: boolean; // implementation of closeSource
    sourceToTargetMappings!: SourceToTargetMapping[]; // implementation of part 'sourceToTargetMappings'

    constructor(id?: string) {
        super();
        if (!!id) {
            this.$id = id;
        } else {
            this.$id = FreUtils.ID(); // uuid.v4();
        }
        // Both 'observableprim' and 'observableprimlist' change the get and set of the attribute
        // such that the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observableprim(this, "name");
        this.name = "";
        observableprim(this, "sourcePage");
        this.sourcePage = "";
        observableprim(this, "targetPage");
        this.targetPage = "";
        observableprim(this, "closeSource");
        this.closeSource = false;

        // Both 'observablepart' and 'observablepartlist' change the get and set of the attribute
        // such that the parent-part relationship is consistently maintained,
        // and make sure the part is observable. In lists no 'null' or 'undefined' values are allowed.
        observablepartlist(this, "sourceToTargetMappings");

        // Make copy method a mobx action
        makeObservable(this, {
            copy: action,
        });
    }

    /**
     * Returns the metatype of this instance in the form of a string.
     */
    freLanguageConcept(): string {
        return this.$typename;
    }

    /**
     * Returns the unique identifier of this instance.
     */
    freId(): string {
        return this.$id;
    }

    /**
     * Returns true if this instance is a model concept.
     */
    freIsModel(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a model unit.
     */
    freIsUnit(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is an expression concept.
     */
    freIsExpression(): boolean {
        return false;
    }

    /**
     * Returns true if this instance is a binary expression concept.
     */
    freIsBinaryExpression(): boolean {
        return false;
    }
    /**
     * A convenience method that copies this instance into a new object.
     */
    copy(): RobotMapping {
        const result = new RobotMapping();
        if (notNullOrUndefined(this.name)) {
            result.name = this.name;
        }
        if (notNullOrUndefined(this.sourcePage)) {
            result.sourcePage = this.sourcePage;
        }
        if (notNullOrUndefined(this.targetPage)) {
            result.targetPage = this.targetPage;
        }
        if (notNullOrUndefined(this.closeSource)) {
            result.closeSource = this.closeSource;
        }
        if (notNullOrUndefined(this.sourceToTargetMappings)) {
            this.sourceToTargetMappings.forEach((x) => result.sourceToTargetMappings.push(x.copy()));
        }
        return result;
    }
    /**
     * Matches a partial instance of this class to this object
     * based on the properties defined in the partial.
     * @param toBeMatched
     */
    public match(toBeMatched: Partial<RobotMapping>): boolean {
        let result: boolean = true;
        if (result && toBeMatched.name !== null && toBeMatched.name !== undefined && toBeMatched.name.length > 0) {
            result = result && this.name === toBeMatched.name;
        }
        if (result && toBeMatched.sourcePage !== null && toBeMatched.sourcePage !== undefined && toBeMatched.sourcePage.length > 0) {
            result = result && this.sourcePage === toBeMatched.sourcePage;
        }
        if (result && toBeMatched.targetPage !== null && toBeMatched.targetPage !== undefined && toBeMatched.targetPage.length > 0) {
            result = result && this.targetPage === toBeMatched.targetPage;
        }
        if (result && toBeMatched.closeSource !== null && toBeMatched.closeSource !== undefined) {
            result = result && this.closeSource === toBeMatched.closeSource;
        }
        if (result && notNullOrUndefined(toBeMatched.sourceToTargetMappings)) {
            result = result && matchElementList(this.sourceToTargetMappings, toBeMatched.sourceToTargetMappings);
        }
        return result;
    }
}
