// Generated by the Freon Language Generator.
export { StudyConfigurationModelEnvironment as LanguageEnvironment } from "./config/StudyConfigurationModelEnvironment.js";
export * from "./language/index.js";
