// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { ScopingExampleDefaultWorker } from "../freon/utils/index.js";
import { type ScopingExampleCheckerInterface } from "../freon/validator/ScopingExampleValidator.js";

export class CustomScopingExampleValidator extends ScopingExampleDefaultWorker implements ScopingExampleCheckerInterface {
    errorList: FreError[] = [];
}
