// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError, FreErrorSeverity } from "@freon4dsl/core";

import { StudyConfigurationModelDefaultWorker } from "../freon/utils/index.js";
import { type StudyConfigurationModelCheckerInterface } from "../freon/validator/StudyConfigurationModelValidator.js";

export class CustomStudyConfigurationModelValidator
    extends StudyConfigurationModelDefaultWorker
    implements StudyConfigurationModelCheckerInterface
{
    errorList: FreError[] = [];
}
