// Generated by the Freon Language Generator.
// TEMPLATE: ValidatorTemplate.generateCustomValidator

import { FreError } from "@freon4dsl/core";

import { StudyConfigurationModelDefaultWorker } from "../freon/utils/index.js";
import { type StudyConfigurationModelCheckerInterface } from "../freon/validator/StudyConfigurationModelValidator.js";
import { Event, UnscheduledEvent, Step, Task, Reference, StaffRole, SystemAccess, Period } from "../freon/language/index.js";

export class CustomStudyConfigurationModelValidator
  extends StudyConfigurationModelDefaultWorker
  implements StudyConfigurationModelCheckerInterface
{
  errorList: FreError[] = [];

  private removeErrorsMatching(pattern: RegExp, logMessage: string): void {
    // Remove all errors matching the pattern (iterate backwards to safely remove while iterating)
    for (let i = this.errorList.length - 1; i >= 0; i--) {
      if (pattern.test(this.errorList[i].message)) {
        console.log(logMessage, this.errorList[i].message);
        this.errorList.splice(i, 1);
      }
    }
  }

  public override execAfterEvent(_modelelement: Event): boolean {
    super.execAfterEvent(_modelelement);
    // Remove alternativeName errors for Events
    this.removeErrorsMatching(
      /Property 'alternativeName' of .* must have a value/,
      "Removing alternativeName error:"
    );
    // Remove description errors for Events
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterUnscheduledEvent(_modelelement: UnscheduledEvent): boolean {
    super.execAfterUnscheduledEvent(_modelelement);
    // Remove alternativeName errors for UnscheduledEvents
    this.removeErrorsMatching(
      /Property 'alternativeName' of .* must have a value/,
      "Removing alternativeName error:"
    );
    // Remove description errors for UnscheduledEvents
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterStep(_modelelement: Step): boolean {
    super.execAfterStep(_modelelement);
    // Remove description errors for Steps
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterTask(_modelelement: Task): boolean {
    super.execAfterTask(_modelelement);
    // Remove description errors for Tasks
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterReference(_modelelement: Reference): boolean {
    super.execAfterReference(_modelelement);
    // Remove description errors for References
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterStaffRole(_modelelement: StaffRole): boolean {
    super.execAfterStaffRole(_modelelement);
    // Remove description errors for StaffRole
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterSystemAccess(_modelelement: SystemAccess): boolean {
    super.execAfterSystemAccess(_modelelement);
    // Remove description errors for SystemAccess
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }

  public override execAfterPeriod(_modelelement: Period): boolean {
    super.execAfterPeriod(_modelelement);
    // Remove description errors for Period
    this.removeErrorsMatching(
      /property 'description' of .* must have a value/i,
      "Removing description error:"
    );
    return false;
  }
}
