// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generateCustomIndex(...)
export * from "./CustomTest1Actions.js";
export * from "./CustomTest1Projection.js";
export * from "./CustomTest1Scoper.js";
export * from "./CustomTest1Stdlib.js";
export * from "./CustomTest1TyperPart.js";
export * from "./CustomTest1Validator.js";
export * from "./FreonConfiguration.js";
export * from "./Test1Interpreter.js";
export * from "./MainTest1Interpreter.js";
