name: Build/Deploy Server

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install all dependencies
        run: npm install --workspaces
        working-directory: .

      - name: Build all packages using TypeScript project references
        run: npm run build
        working-directory: .
        env:
          DEBUG: "*" 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            packages/server/dist
            packages/server/web.config
            packages/server/package.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: server-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZUREAPPSERVICE_CLIENTID }}","clientSecret":"${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}","subscriptionId":"${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}","tenantId":"${{ secrets.AZUREAPPSERVICE_TENANTID }}"}'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'crchub-server'
          package: server-app