// Generated by the Freon Language Generator.
// TEMPLATE: ConfigurationTemplate.generate(...)

import { type FreProjection, type FreCombinedActions, type FreTyper, type FreStdlib, type FreScoper } from "@freon4dsl/core";

import { CustomPrimsActions } from "./CustomPrimsActions.js";
import { CustomPrimsProjection } from "./CustomPrimsProjection.js";
import { CustomPrimsScoper } from "./CustomPrimsScoper.js";
import { CustomPrimsTyperPart } from "./CustomPrimsTyperPart.js";
import { CustomPrimsValidator } from "./CustomPrimsValidator.js";
import { CustomPrimsStdlib } from "./CustomPrimsStdlib.js";
import { type PrimsCheckerInterface } from "../freon/validator/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customizations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomPrimsProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomPrimsActions()];
    // add your custom validations here
    customValidations: PrimsCheckerInterface[] = [new CustomPrimsValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomPrimsScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomPrimsTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomPrimsStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
